### DISCUSSION TITLE
Does Oathkeeper support multiple domains?

### DISCUSSION THREAD

**Discussion by shreeharsha-factly** [ory/oathkeeper#1012] [Q&A] [answered]
For example
```
serve:
  admin:
    cors:
      enabled: true
      allowed_origins:
        - https://domain-one.com
        - https://domain-two.com
```
