### DISCUSSION TITLE
Multi-tenancy with Oathkeeper

### DISCUSSION THREAD

**Discussion by markrepedersen** [ory/oathkeeper#733] [Q&A] [answered]
I'm using Oathkeeper with Kratos (following this guide: https://www.ory.sh/kratos/docs/guides/zero-trust-iap-proxy-identity-access-proxy/) to create a multi-tenant application. To support multi-tenancy, it seems like I would need to create a Kratos instance for each tenant and then have Oathkeeper route requests to the respective Kratos instance based on the URL path, which would require specifying multiple authentication servers in the Oathkeeper configuration.

Is it possible to do this with Oathkeeper and, if so, can someone give an example of how to do it?

Thanks!

**Comment by Benehiko** [comment, marked as answer]
Hi @markrepedersen,

I believe you can override the global oathkeeper configurations file inside your access rule as specified [here](https://www.ory.sh/oathkeeper/docs/pipeline/authn#cookie_session).

This is your global `cookie_session` config:
```
# Global configuration file oathkeeper.yml
authenticators:
  cookie_session:
    # Set enabled to true if the authenticator should be enabled and false to disable the authenticator. Defaults to false.
    enabled: true
    config:
      check_session_url: https://session-store-host
```

This is your overridden `cookie_session` config
```
# Some Access Rule: access-rule-1.yaml
id: access-rule-1
# match: ...
# upstream: ...
authenticators:
  - handler: cookie_session
    config:
      check_session_url: https://session-store-host
      only:
        - sessionid
```
