### DISCUSSION TITLE
Configure Oathkeeper  Kratos and Hydra

### DISCUSSION THREAD

**Discussion by DZhurybida** [ory/oathkeeper#734] [Q&A] [answered]
Is it possible to have more than one `bearer_token` authenticator?

I want to use Hydra and Kratos API flow, and they both use the `Authentication` header.

Some context: I want to use Hydra for Oath2,  and Kratos API flow for e2e tests of API to create test users.

**Comment by Benehiko** [comment, marked as answer]
Hi @DZhuribeda 

I believe this question is similar to this one https://github.com/ory/oathkeeper/discussions/733

Just let me know if you require more assistance :)

**Reply by DZhurybida** [reply]
Hi, @Benehiko 

Sorry for the late response, as I understand, I should be able to do something like that:
```
# Some Access Rule: access-rule-1.yaml
id: access-rule-1
# match: ...
# upstream: ...
authenticators:
# default config will be used to 
  - handler: bearer_token
# override config
  - handler: bearer_token
    config:
      check_session_url: https://some-non-default
```

Can you confirm that I correctly understand?
