### DISCUSSION TITLE
Customizable error messages output

### DISCUSSION THREAD

**Discussion by insotriplesix** [ory/oathkeeper#747] [Q&A] [answered]
Salute! \0

I need to change the default template of error messages like `403 Forbidden` or `404 NotFound` from this:
```json
{
  "error": {
    "code": 403,
    "status": "Forbidden",
    "message": "Access credentials are not sufficient to access this resource"
  }
}
```
to my own. 

During the investigation I found [this thread](https://community.ory.sh/t/oathkeeper-default-error-message/1310) where Arthur already asked the same question. Further, the issue was resolved by _hackerman_ in [this commit](https://github.com/ory/oathkeeper/commit/4033321b13671de8d0d5a42846a4e19d6065db62) where he added customizable error handlers. I took a glance to the code he wrote, read the documentation & tried to figured out how these changes can help me to solve the problem, but I still don't get it.

So, is it even possible to change the body of an error output? E.g. do something like this in the config file:
```yaml
errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        error_template: file:///path/to/my-error-template.json
```

If Arthur's issue was closed then I assume that it is possible to do.. somehow. I also found [this article](https://blog.getambassador.io/part-2-api-access-control-and-authentication-with-kubernetes-ambassador-and-ory-oathkeeper-q-a-127fa57f6332) where Daniel have error responses like this one:
```json
{
  "error": {
    "code": 404,
    "status": "Not Found",
    "request": "84a2b164-7229-4f69-a0cd-227611c07128",
    "message": "Requested url does not match any rules"
  }
}
```
and because of the `request` field I suggest that an error output can vary and be configured or something.

BTW if it's not possible yet, I already tried to achieve this in a different way - with the `redirect` handler:
```yaml
errors:
  fallback:
    - redirect
  handlers:
    redirect:
      enabled: true
      config:
        to: https://my.domain.com/403.json
```
Finally, It allowed me to get the output of an error message I wanted to, but there are also some problems with it: 
1) The "real" HTTP response status after successful redirection is `200 OK`, so it's a bit confusing, and not what I actually want, because the body is:
```json
{
  "message": "Operation not allowed",
  "code": 403,
  "errors": []
}
```
2) What if I want to redirect `403 Forbidden` errors to https://my.domain.com/403.json and `404 NotFound` to https://my.domain.com/404.json ? How can I achieve this? This is how I (approximately) tried to:
```yaml
errors:
  fallback:
    - redirect
  handlers:
    redirect:
      enabled: true
      config:  
        when:
          - error: forbidden
            to: https://my.domain.com/403.json
          - error: not_found
            to: https://my.domain.com/404.json
```
Neither the documentation nor different keyword combinations, permutations, indents helped me. It just doesn't work. ¯\\_(ツ)_/¯
