### DISCUSSION TITLE
Add introspection_request_headers based on secret

### DISCUSSION THREAD

**Discussion by PeteMac88** [ory/oathkeeper#807] [Q&A] [answered]
Hey there,
we are using oathkeeper together with keycloak in kubernetes. We are following the gitops process and hold all our helm file configuration in github repos.

In order to access the `introspect` we need to add a base64 encoded Authorization header through the `introspection_request_headers` configuration. Problem here is that I need to add the base64 string as plain text in the oathkeeper access-rule config in the helm values which is kind of ugly and unsecure. Is there a way to set specifi configuration which normally requieres secret values through environment or k8s secrets?

**Comment by vinckr** [comment]
Hey Pete,
sorry for the late answer. 
Not an expert on k8s and configuration, you can load the config files from another source with the `-c path/to/config.yaml` flag. 
@Demonsthere: maybe you know a better solution here?

**Comment by Demonsthere** [comment, marked as answer]
Hi there! 
I think that was you're trying to achieve is possible within our charts. Oathkeeper allows you to define [extraEnvs](https://github.com/ory/k8s/blob/master/helm/charts/oathkeeper/values.yaml#L182), so you could just add it like 

```yaml
    extraEnv:
      - name: AUTHENTICATORS_OAUTH2_INTROSPECTION_CONFIG_INTROSPECTION_REQUEST_HEADERS
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: mykey
```
