### DISCUSSION TITLE
Remote JSON example

### DISCUSSION THREAD

**Discussion by rezakazemi928** [ory/oathkeeper#814] [Q&A] [answered]
Hi.
I am really keen on using Oathkeeper authorization in my project, and I need a little help to code.
I want to use the remote JSON. However, It is not clear how can I send the payload along with my authorization remote Link. Would you mind give me some specifics about the configurations in the YML file, please?
Thanks

**Comment by vinckr** [comment, marked as answer]
Hey,
Are you asking how to configure the oathkeeper.yml to use remote JSON?
Can you give me some details on the "authorization remote Link"? What is this exactly? 

There are some examples [in the docs](https://www.ory.sh/oathkeeper/docs/pipeline/authz/#remote_json), but you probably already did not find what you are looking for in there. 
`The authorizer makes a HTTP POST request to a remote endpoint with a JSON body. `
Payload:
`payload (string, required) - The request's JSON payload sent to the remote authorizer. The string will be parsed by the Go text/template package and applied to an AuthenticationSession object. See Session for more details.`

**Reply by rezakazemi928** [reply]
Thank you so much for your response.
Sure,
I have a link for my access rule which I coded myself with flask API. it would send a post request and check the request body with my access rules template. 
something like this: 
```
"identity_users": [
            {
                "id": "fd5f2992-a4fe-4b08-ae41-9619aa24bd71",
                "username": "reza7898"
            }
        ],
        "identity_groups": [],
        "id": "face9adf-c703-4f98-b15f-5a7d673ddc70"
```
and my config file for Oauthkeeper:
```
authorizers:
  allow:
    enabled: true
  remote_json:
    enabled: true
    config:
      remote: http://127.0.0.1:5000/api/accessrules/authorization # or the docker container IP address
      payload: "{}"
```

I do not know what should I do in the payload field in my case.
I read the documentation, but still, I am a little confused.
