### DISCUSSION TITLE
What happens when the url matches multiple access rules?

### DISCUSSION THREAD

**Discussion by spietras** [ory/oathkeeper#934] [Q&A] [answered]
Let's say:

```
- id: allow-rule
  match:
    url: "<.*>"
  authorizer:
    handler: allow
- id: deny-rule
  match:
    url: "<.*>"
  authorizer:
    handler: deny
```

Will it be detected at startup and some error reported? Or the first match will be used (thus allowing all requests in this case)?

Couldn't find an answer in the documentation.
