### DISCUSSION TITLE
Empty Headers from Hydrator

### DISCUSSION THREAD

**Discussion by tschlaepfer** [ory/oathkeeper#942] [Q&A] [answered]
Hi @vinckr, I have set up a hydrator mutator within Oathkeeper, the goal is forward a custom header (X-TENANT-ID) to the backend application. I can confirm the presents of the header in the backend application. However, the header is always empty and it seems that I'm not the only one experiencing this issue, https://github.com/ory/oathkeeper/issues/380#issuecomment-1074285960. Do you have an idea what I'm doing wrong or if this is a known issue?

**Comment by alan994** [comment]
Have the same problem myself. Here is my configs.

`Ory Oath Keeper Access Rule`
```
- id: "alan:api:auth:old"
  upstream:
    preserve_host: false # this will ensure we use host and port of `url` property bellow
    url: "http://host.docker.internal:5292" #5291
    strip_path: "/api/old"
  match:
    url: "http://127.0.0.1:4455/api/old/secure"
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: hydrator
```
Ory Oath Keeper config - section mutators. Only Hydrator is important
```
mutators:
  noop:
    enabled: true

  hydrator:
    enabled: true
    config:
      api:
        url: http://host.docker.internal:5292/ory

  id_token:
    enabled: true
    config:
      issuer_url: http://127.0.0.1:4455/
      jwks_url: file:///etc/config/oathkeeper/id_token.jwks.json
      claims: |
        {
          "session": {{ .Extra | toJson }}
        }

  header:
    enabled: true
    config:
      headers:
        X-UserId: "{{ print .Subject }}"
        X-CompanyName: "{{ print .Extra.CompaynId }}"
```

My .NET service that hydrator mutator calls
```
app.MapPost("/ory", async (HttpContext httpContext, [FromBody] OryPayload payload, [FromServices] ILogger<Program> logger) =>
{
    logger.LogInformation("Payload from Ory: {@Payload}", payload);

    httpContext.Response.StatusCode = 200;

    if (payload.Header is null)
    {
        payload.Header = new Dictionary<string, object>();
    }

    payload.Header.Add("x-tl-user-id", new string[] { "alan994" });
    payload.Header.Add("x-tl-company-id", new string[] { "aj-solutions", "talentlyft" });


    return payload;
});
```

**Comment by tschlaepfer** [comment]
This is my configuration.

The oathkeeper config is: 
```
mutators:
  noop:
    enabled: true
  header:
    enabled: false
  hydrator:
    enabled: true
    config:
      api:
        url: http://demo.ms.svc.cluster.local:8080/as/device-info
        retry:
          give_up_after: 1s
          max_delay: 200ms
      cache:
        ttl: 60s
```

and the rule configuration is:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: demo-rules
data:
  token_rule.yaml: |
    - id: demo-token-rule
      upstream:
        url: http://demo.idp.svc.cluster.local:8080/idp/token
        preserve_host: false
        strip_path: /as/token
      match:
        url: http://demo.apps.dev/as/token
        methods:
          - POST
      authenticators:
        - handler: jwt
      authorizer:
        handler: remote
        config:
          remote: http://demo.ms.svc.cluster.local:8080/as/authz
      mutators:
        - handler: hydrator
          config:
            api:
              url: http://demo.ms.svc.cluster.local:8080/as/device-info
        - handler: id_token
          config:
            issuer_url: demo-client
            ttl: 10s
            claims: '{"aud": ["https://demo.apps.dev/oauth2/token"]}'
      errors:
        - handler: json
```

In the logs of the mircoservice that provides the information for the hydrator I can see that the X-TENANT-ID header is set correctly: 
```
{"match_context":{"regexp_capture_groups":[],"url":{"Path":"/as/token","Scheme":"http","User":null,"Opaque":"","ForceQuery":false,"RawQuery":"","RawFragment":"","Host":"demo.apps.dev","RawPath":"","Fragment":""}},"subject":"demo-client","extra":{"scp":[],"sub":"demo-client"},"header":{"X-TENANT-ID":["demo"]}} 
```

**Comment by vinckr** [comment]
Hey folks, thanks for opening the discussion and the extra info. 
I am currently doing some exploration, not being super familiar with hydrator. 

Here is another issue with the same problem:
https://github.com/ory/oathkeeper/issues/582

I found these earlier discussions with a similar issues: 

https://github.com/ory/oathkeeper/discussions/901
https://github.com/ory/oathkeeper/issues/851
https://github.com/ory/oathkeeper/issues/793

**Comment by alan994** [comment]
Hi @vinckr,
I looked at the links you attached. It seems to me that all of them are having issues with `header` mutator, not with the `hydrator`. In our case, we don't need a `header` mutator because `hydrator` should change [`AuthenticationSession`](https://github.com/ory/oathkeeper/blob/master/pipeline/authn/authenticator.go#L39) object directly and whatever is in `header` map should be propagated to upstream API. And it is but without value :( 

Did you try to reproduce this issue yourself? Can we help somehow?

**Reply by vinckr** [reply]
Hey Alan, 
you are right, 

Here is also an older relevant issue: https://github.com/ory/oathkeeper/issues/299 , and it seems the headers should be forwarded correctly? (see also [this PR](https://github.com/ory/oathkeeper/pull/479/files))

I did not get around to reproduce it, it would help greatly if you could share a repo with a simple config that reproduces the error. 
Also tagging @gen1us2k, did you run into this before by any chance?

**Reply by gen1us2k** [reply]
Hello there. 
I built a simple example with Go, oathkeeper, and Kratos. 
I have a service hello and I want to proxy only authenticated and mutated requests to this service. The code is simple and you can find it [here](https://github.com/gen1us2k/hydrator_example/blob/master/service/main.go)

An example of [hydrator](https://github.com/gen1us2k/hydrator_example/blob/master/hydrator/main.go) that sets a custom and hardcoded header.

Oathkeeper config
```
log:
  level: debug
  format: json

serve:
  proxy:
    cors:
      enabled: true
      allowed_origins:
        - "*"
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type
      allow_credentials: true
      debug: true

errors:
  fallback:
    - json

  handlers:
    redirect:
      enabled: true
      config:
        to: http://127.0.0.1:4455/login
        when:
          -
            error:
              - unauthorized
              - forbidden
            request:
              header:
                accept:
                  - text/html
    json:
      enabled: true
      config:
        verbose: true

access_rules:
  matching_strategy: regexp
  repositories:
    - file:///etc/config/oathkeeper/access-rules.yml

authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest

  cookie_session:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
      only:
        - ory_kratos_session

  noop:
    enabled: true

authorizers:
  allow:
    enabled: true

mutators:
  noop:
    enabled: true
  hydrator:
    enabled: true
    config:
      api:
        url: http://hydrator:8090/hydrate
```
Access rules

```
-
  id: "api:service:protected"
  upstream:
    preserve_host: true
    url: "http://service:8090"
  match:
    url: "http://127.0.0.1:8080/hello"
    methods:
      - GET
  authenticators:
    -
      handler: cookie_session
  mutators:
    - handler: hydrator
  authorizer:
    handler: allow
  errors:
    - handler: redirect
      config:
        to: http://127.0.0.1:4455/login
```

You can check an example for now, but my next steps are to have a similar configuration that you have
