### ISSUE TITLE
Regex path matching isn't working.

### ISSUE THREAD

**Issue by KieronWiltshire** [ory/oathkeeper#1095]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I have two of these matching rules:

This is for kratos
```
"url": "<(http|https):\\/\\/([\\w-]+(\\.[\\w-]+)*|[\\d.]+)(:\\d+)?\\/\\.ory\\/kratos\\/public(\\/.*|(\\?.*)?)?$>"
```

This is for my custom service
```
"url": "<(http|https):\\/\\/([\\w-]+(\\.[\\w-]+)*|[\\d.]+)(:\\d+)?\\/api\\/account(\\/.*|(\\?.*)?)?$>"
```

Both are configured identically, I've even tried swapping them around and one thing always remains constant. The .ory regex is the only one that works. If i switch /api/account to /.api/account that appears to work. So I thought, okay it must be an issue with my regex, but no when I swap the match paths to literal strings like `http://localhost:4455/api/account` and go to this URL in the browser, I get the exact same error

```
{"error":{"code":404,"status":"Not Found","message":"Requested url does not match any rules"}}
```

### Reproducing the bug

Honestly no idea, but I'm using the latest ory oathkeeper docker image and my config files are as follows:

docker-compose.yml
```
version: "3.9"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./.docker-compose/data/timescaledb:/var/lib/postgresql/data
    networks:
      - dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./.docker-compose/data/redis:/data
    networks:
      - dev

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - timescaledb
    ports:
      - 8080:80
    environment:
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_DEFAULT_EMAIL=admin@admin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - ./.docker-compose/data/pgadmin:/var/lib/pgadmin
    networks:
      - dev

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    depends_on:
      - redis
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379:1
    networks:
      - dev

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    container_name: mailslurper
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - dev

  hydra-migrate:
    image: oryd/hydra:latest
    container_name: hydra-migrate
    restart: on-failure
    depends_on:
      - timescaledb
    command:
      migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    environment:
      DSN: postgres://postgres:password@timescaledb:5432/ory-hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      -
        type: bind
        source: ./.docker-compose/configs/ory/hydra
        target: /etc/config/hydra
    networks:
      - dev

  kratos-migrate:
    image: oryd/kratos:latest
    container_name: kratos-migrate
    restart: on-failure
    depends_on:
      - timescaledb
    command:
      migrate -c /etc/config/kratos/kratos.yml sql -e --yes
    environment:
      DSN: postgres://postgres:password@timescaledb:5432/ory-kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      LOG_LEVEL: debug
    volumes:
      -
        type: bind
        source: ./.docker-compose/configs/ory/kratos
        target: /etc/config/kratos
    networks:
      - dev

  hydra:
    image: oryd/hydra:latest
    container_name: hydra
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    command:
      serve -c /etc/config/hydra/hydra.yml all --dev
    environment:
      DSN: postgres://postgres:password@timescaledb:5432/ory-hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES: public
      LOG_LEVEL: trace
    volumes:
      -
        type: bind
        source: ./.docker-compose/configs/ory/hydra
        target: /etc/config/hydra
    ports:
      - 4444:4444
      - 4445:4445
      - 5555:5555
    networks:
      - dev

  kratos:
    image: oryd/kratos:latest
    container_name: kratos
    restart: unless-stopped
    depends_on:
      - kratos-migrate
    command: serve -c /etc/config/kratos/kratos.yml --dev
    environment:
      DSN: postgres://postgres:password@timescaledb:5432/ory-kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      LOG_LEVEL: trace
    volumes:
      -
        type: bind
        source: ./.docker-compose/configs/ory/kratos
        target: /etc/config/kratos
    ports:
      - 4433:4433
      - 4434:4434
    networks:
      - dev

  oathkeeper:
    image: oryd/oathkeeper:latest
    container_name: oathkeeper
    restart: unless-stopped
    depends_on:
      - timescaledb
    command: serve --config=/etc/config/oathkeeper/oathkeeper.yml
    environment:
      - LOG_LEVEL=debug
      - LOG_LEAK_SENSITIVE_VALUES="true"
      - TRACING_PROVIDER=jaeger
      - TRACING_SERVICE_NAME=Oathkeeper
      - TRACING_PROVIDERS_JAEGER_SAMPLING_SERVER_URL=http://jaeger:5778/sampling
      - TRACING_PROVIDERS_JAEGER_LOCAL_AGENT_ADDRESS=jaeger:6831
      - TRACING_PROVIDERS_JAEGER_SAMPLING_TYPE=const
      - TRACING_PROVIDERS_JAEGER_SAMPLING_VALUE=1
    volumes:
      - type: bind
        source: ./.docker-compose/configs/ory/oathkeeper
        target: /etc/config/oathkeeper
    ports:
      - 4455:4455
      - 4456:4456
    networks:
      - dev

  jaeger:
    image: jaegertracing/all-in-one:1.22
    container_name: jaeger
    ports:
      - 16686:16686
#     These are ports for collecting, sampling, agents, ...
#      - "5775:5775/udp"
#      - "6831:6831/udp"
#      - "6832:6832/udp"
#      - "5778:5778"
#      - "14268:14268"
#      - "9411:9411"
    networks:
      - dev

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./.docker-compose/configs/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "1234:1234"
    networks:
      - dev

networks:
  dev:
    driver: bridge
```

Here is my .docker-compose/configs directory with my config files inside
[configs.zip](https://github.com/ory/oathkeeper/files/11238010/configs.zip)

### Relevant log output

```shell
I'm not sure how to access the logs, there isn't enough documentation around this or in fact a majority of things.
```

### Version

latest

### On which operating system are you observing this issue?

Windows

### In which environment are you deploying?

Docker Compose

### Additional Context

Please help, I'm in the slack, I follow the issues on github, but the lack of support and relevant documentation for this and other ory projects make it really difficult for anyone to adopt. Which is really annoying because I like the idea behind the way this works.
