### ISSUE TITLE
Oathkeeper bombards Ory Network with requests after upgrade to 40.x

### ISSUE THREAD

**Issue by Withel** [ory/oathkeeper#1161]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Ory Network Project

https://vibrant-dubinsky-6d1qtx5k0i.projects.oryapis.com

### Describe the bug

After upgrading from 39.4 to 40.7, @tricky42 notified us, about huge amount of requests made from oathkeeper to ory network's /introspect endpoint, as can be seen on the first screenshot (Upgrade was performed on 23.04 at ~15:58). From our perspective we don't see any issues in the logs or metrics. On the second screenshot you can see oathkeeper traffic (spike is from the moment of upgrade). We didn't change any configuration between the versions (except the naming of log level), and we suspect that the cache might not be working properly. 

Screenshot 1:
![image](https://github.com/ory/oathkeeper/assets/32665405/1a1fcce0-33e6-4975-847c-bf9795771301)

Screenshot 2:
![image](https://github.com/ory/oathkeeper/assets/32665405/b7d5f1b0-b840-450f-866c-65b0662f3c56)

### Reproducing the bug

1. Upgrade oathkeeper to 40.7 from 39.x 

### Relevant configuration

```yml
authenticators:
    oauth2_introspection:
      config:
        cache:
          enabled: true
          max_cost: 100
          ttl: 1h
        introspection_request_headers:
          Authorization: [REDACTED]
        introspection_url: https://[REDACTED]/admin/oauth2/introspect
        retry:
          give_up_after: 3s
          max_delay: 500ms
        token_from:
          header: Authorization
      enabled: true
```

### Version

40.7

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

Kubernetes with Helm
