### ISSUE TITLE
Oathkeeper docker-compose.yaml outdated env vars

### ISSUE THREAD

**Issue by cerealkill** [ory/oathkeeper#1164]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Oathkeeper default [docker-compose.yml](https://github.com/ory/oathkeeper/blob/master/docker-compose.yml#L13C1-L17C49) have outdated metric variables  

### Reproducing the bug

```
git clone git@github.com:ory/oathkeeper.git
cd oathkeeper
docker compose up
```

### Relevant log output

```shell
oathkeeper                  | {"audience":"application","error":{"message":"missing port in address","stack_trace":"stack trace could not be recovered from error type *net.AddrError"},"level":"fatal","msg":"Unable to initialize Tracer for Oathkeeper.","service_name":"ORY Oathkeeper","service_version":"v0.40.7","time":"2024-05-14T09:19:08.243127416Z"}
```

### Relevant configuration

```yml
services:
  oathkeeper:
    environment:
      - TRACING_PROVIDER=jaeger
      - TRACING_PROVIDER_JAEGER_SAMPLING_SERVER_URL=http://jaeger:5778/sampling
      - TRACING_PROVIDER_JAEGER_LOCAL_AGENT_ADDRESS=jaeger:6831
      - TRACING_PROVIDER_JAEGER_SAMPLING_TYPE=const
      - TRACING_PROVIDER_JAEGER_SAMPLING_VALUE=1
```

### Version

0.40.7

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

### Additional Context

Env vars changed, to fix just change to:
```
services:
  oathkeeper:
    environment:
      - TRACING_PROVIDER=jaeger
      - TRACING_PROVIDERS_JAEGER_SAMPLING_SERVER_URL: http://jaeger:5778/sampling
      - TRACING_PROVIDERS_JAEGER_LOCAL_AGENT_ADDRESS: jaeger:6831
```
