### ISSUE TITLE
Upgrade Oathkeeper helm chart 0.41 causes 503

### ISSUE THREAD

**Issue by WoodyWoodsta** [ory/oathkeeper#1165]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Ory Network Project

N/A

### Describe the bug

Upgrading the Oathkeeper chart to 0.41.0 causes oathkeeper to restart after 503 health check. I've not changed anything in the chart, and I don't use the secret (so it's `secret.false` for me).

### Reproducing the bug

Upgrade to chart 0.41.0, with `secret.false`

### Relevant configuration

```yml
oathkeeper:
  oathkeeper:
    config:
      log:
        level: debug
      authenticators:
        noop:
          enabled: true
        cookie_session:
          enabled: true
          config:
            check_session_url: http://ory-kratos-public:80/sessions/whoami
            preserve_path: true
            subject_from: "identity.id"
            only:
              - ory_kratos_session
        oauth2_client_credentials:
          enabled: true
          config:
            token_url: http://ory-hydra-public.ory.svc.cluster.local:4444/oauth2/token
            cache:
              enabled: true
      errors:
        handlers:
          redirect:
            enabled: true
            config:
              to: ***/login
          json:
            enabled: true
          www_authenticate:
            enabled: true
            when:
              - error:
                  - unauthorized
        fallback:
          - json
      authorizers:
        allow:
          enabled: true
        remote_json:
          enabled: true
          config:
            remote: http://ory-keto-read.ory.svc.cluster.local:80/relation-tuples/check
            payload: ""
      mutators:
        noop:
          enabled: true
      serve:
        proxy:
          trust_forwarded_headers: true
          timeout:
            write: 1m
            read: 1m
            idle: 1m
          cors:
            enabled: true
            allowed_origins:
              - ***
    managedAccessRules: false
  maester:
    enabled: false
  serviceMonitor:
    enabled: false
  deployment:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 1Gi
```

### Version

0.41.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

Kubernetes with Helm
