### ISSUE TITLE
Multiple authorizers

### ISSUE THREAD

**Issue by renom** [ory/oathkeeper#1194]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe your problem

At the moment it's only possible to set up a single authorizer in access rules:
```yaml
  authorizer:
    handler: allow
```

### Describe your ideal solution

Support specifying multiple authorizers:
```yaml
  authorizers:
    - handler: remote_json # authorizer 1
    # config here
    - handler: remote_json # authorizer 2
    # config here
```

### Workarounds or alternatives

\-

### Version

v0.40.7
