### ISSUE TITLE
More Customizable collapse_request_path Setting

### ISSUE THREAD

**Issue by WillyRL** [ory/oathkeeper#1212]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe your problem

In reference to [issue #446](https://github.com/ory/oathkeeper/issues/446), the collapse_request_path configuration could be significantly more useful if it were more flexible.

**Use Case**
I have an /api prefix for my service, followed by a unique UUID in the URL path, for example:

```
/api/conversations/{uuid-v4-conversation-id}/messages
```

When collapse_request_path is set to false, my metrics become unmanageable because each unique UUID generates a separate metric entry. However, setting it to true collapses everything under the /api prefix, losing valuable details for different endpoints.

### Describe your ideal solution

Enable a more advanced configuration for collapse_request_path that allows specifying patterns, placeholders, or partial collapsing so that important segments (like /conversations) are preserved while unique identifiers (UUIDs) are collapsed.

**Example Configuration**
```
  collapse_request_paths:
    enabled: true
    rules:
      - pattern: "^/api/conversations/[0-9a-fA-F-]{36}/messages"
        replacement: "/api/conversations/:conversationId/messages"
      - pattern: "^/api/other-service/[0-9a-fA-F-]{36}"
        replacement: "/api/other-service/:resourceId"
```

### Workarounds or alternatives

If the pattern based is too complicated, for the use case that using /api prefix, provide the collapse_level. 
```
  collapse_request_paths:
    enabled: true
    # Define how many path segments to skip from the start
    collapse_level: 1
 ```

### Version

0.40.6
