### ISSUE TITLE
Oathkeeper incorrectly ckeck cookie session requests to Kratos

### ISSUE THREAD

**Issue by fswu0831** [ory/oathkeeper#1222]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

## Description:
I am experiencing an issue where ORY Oathkeeper is routing requests incorrectly. Based on my rules.yml, requests to a specific endpoint should be forwarded to my upstream service, but instead, they are being sent to Kratos unexpectedly. Despite multiple attempts to modify the configuration, Oathkeeper continues to direct traffic incorrectly.

## Steps to Reproduce

1. Define the following rule in `rules.yml`:
   ```yaml
   id: "keto-test"
   upstream:
     preserve_host: true
     url: "https://my-upstream-service.example.com/"
   match:
     url: "https://my-proxy.example.com/test.*"
     methods:
       - GET
       - POST
       - PUT
       - DELETE
   authenticators:
     - handler: cookie_session
       config:
         check_session_url: http://kratos:4433/sessions/whoami
   authorizer:
     handler: allow
   mutators:
     - handler: id_token
   errors:
     - handler: json
   
```

1. Restart Oathkeeper and verify that the rule is applied:
```
curl -X GET http://oathkeeper:4456/rules
```
The rule is correctly listed in the response.

1. Send a request to the /test endpoint:
```
curl -v https://my-proxy.example.com/test
```

1. Observe that instead of being routed to https://my-upstream-service.example.com/, the request is forwarded to http://kratos:4433/test/, which is incorrect.

## Expected Behavior
Check cookie requests should go to `http://kratos:4433/sessions/whoami`

## Actual Behavior
Check cookie requests go to `http://kratos:4433/test` followd by match rule.

### Reproducing the bug

Look at the Describe the bug

### Relevant log output

```shell
## Tcpdump on Kratos

/test HTTP/1.1
Host: kratos:4433
User-Agent: Go-http-client/1.1
Cookie: ory_kratos_continuity=<session>; ory_kratos_session=<session>
Accept-Encoding: gzip
```

### Relevant configuration

```yml

```

### Version

v0.40.9

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None
