### ISSUE TITLE
Implement generic JSON-RPC Authorizer `remote_json`

### ISSUE THREAD

**Issue by aeneasr** [ory/oathkeeper#201]
Currently, we only support the [ORY Keto Authorizer](https://github.com/ory/oathkeeper/blob/master/pipeline/authz/keto_engine_acp_ory.go). Because many developers wish to use other servers (e.g. OPA) we should support them as well.

To solve that, it would make sense to write a generic HTTP-based authorizer. To configure it, we would use the well established Go Template engine we're using for the [ID Token Mutator](https://github.com/ory/oathkeeper/blob/master/pipeline/mutate/mutator_id_token.go#L152-L169)

The configuration should probably be something along these lines:

```yaml
# oathkeeper config.yml

mutators:
  remote_json:
    config:
      remote: http://host/some-path
      payload: |
        {
          "subject": "{{ .Subject }}"
        }
```

The payload is of course configurable and could also be more complex, like

```
{
  "user": "{{ .Subject }}"
  "role": "{{ .Extra["role"] }}"
}
```

and so on.

The authorizer sends the JSON payload to `remote` and expects either 403 or 200 to allow/deny access.
