### ISSUE TITLE
Keto Engine should support multiple subjects

### ISSUE THREAD

**Issue by mvanderlee** [ory/oathkeeper#269]
**Is your feature request related to a problem? Please describe.**

An incoming JWT might have a subject, and a list of roles. To check if a the token is authorized I'd like to be able to check all against the Keto policies.

Example:
JWT: 
```json
{
  "sub": "test@ory.com",
  "roles": [
      "role1",
      "role2"
  ]
}
```
Keto policies (condensed):
```yaml
- subjects: ["test@ory.com"]
  resources: ["/api/reports/50"]

- subjects: ["role1"]
  resources: ["/api/dashboards/daily/*"]

- subjects: ["role2"]
  resources: ["/api/dashboards/monthly/*"]
``` 

Oathkeeper authorizers:
```yaml
- handler: "keto_engine_acp_ory"
  config:
    required_resource: "/api/reports/$1"
    subject: [
      "{{.Subject}}",
      "{{.Extra.roles}}"
    ]

OR

- handler: "keto_engine_acp_ory"
  config:
    required_resource: "/api/dashboards/$1"
    subject: "{{.Subject}}|{{range $i,$a := .Extra.roles}}{{if gt $i 0 }}|{{end}}{{.}}{{end}}"
    subjectDelimiter: "|"
```

subjectDelimiter might work better? I have no idea how to implement it otherwise.

**Describe the solution you'd like**

I'd like Oathkeeper to iterate over the allowed subjects to check if any of them is authorized.
If any of them have an explicit DENY, then that should take precedence.

**Describe alternatives you've considered**

* Forego roles and only assign policies to a user.
* Have a middleman management service that interpret roles and assigns all role policies to the user directly
* Multiple authorizers with `role[$idx]`. But that won't work unless there is a max number of roles a user can be assigned. Even then, it's tedious.
* Forego the Keto engine entirely. Use the `allow` authorizer, and a custom `hydrator` mutator to a track roles independently from the ORY system, and assign hydrated claims to an id_token, that will be passed to the final service which will perform authorization itself based on said claims. 

**Additional context**
