### ISSUE TITLE
Env vars for client ID/secret in oauth2_introspection don't work anymore in v0.19.0-beta.1

### ISSUE THREAD

**Issue by GuillaumeSmaha** [ory/oathkeeper#270]
**Describe the bug**

Setting environment vars `AUTHENTICATORS_OAUTH2_INTROSPECTION_PRE_AUTHORIZATION_CLIENT_ID` and `AUTHENTICATORS_OAUTH2_INTROSPECTION_PRE_AUTHORIZATION_CLIENT_SECRET` doesn't work anymore since `v0.19.0-beta.1`

If I don't put `client_id` and `client_secret` in global configuration, none error is throw at start for the configuration file but the rules will throw an error without information:
`time="2019-09-30T14:47:43Z" level=error msg="A rule uses a malformed configuration and all URLs matching this rule will not work. You should resolve this issue now." error="authenticator matching this route is misconfigured or disabled"` 

Global configuration for `oauth2_introspection`:
```yaml
    authenticators:
      oauth2_introspection:
        enabled: true
        config:
          introspection_url: https://
          scope_strategy: none
          required_scope: []
          pre_authorization:
            enabled: true
            token_url: https://
            scope: []
```

Example of rule:
```yaml
    - id: api
      upstream:
        url: http://backend
        preserve_host: true
      match:
        url: http://domain.com/api
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - HEAD
        - OPTIONS
      authenticators:
      - handler: oauth2_introspection
      authorizer:
        handler: allow
```

**Expected behavior**

Env vars should be allowed for client id and secret to avoid saving secret in git repo.

**Environment**

- Version:`oryd/oathkeeper:v0.19.0-beta.1`

**Additional context**

I think this is related to this commit and lines removal:
https://github.com/ory/oathkeeper/commit/89709aabfe002fc5ae2e76016fc45a13d74f3d8b#diff-2449a6ea083767b149400840c05f41bdL58-L59
