### ISSUE TITLE
Customizable on unauthenticated, forbidden, route not found, and other error handlers

### ISSUE THREAD

**Issue by aeneasr** [ory/oathkeeper#284]
This is a proposal and we encourage you to participate. Please share your thoughts with us by commenting on this issue.

**Is your feature request related to a problem? Please describe.**

Right now, all errors are handled equally. They will be relayed to the client making the request as application/json with some error content:

- If the client is not authenticated (or invalid credentials), the client receives an application/json response with an explanation.
- If the client is not allowed to make the request, the client receives an application/json response with an explanation.
- If the client is requesting a route that is not configured in Oathkeeper, the client receives an application/json response with an explanation.
- If Oathkeeper is encountering an error (e.g. upstream not working, ...), the client receives an application/json response with an explanation.

**Describe the solution you'd like**

Additional to the above, we would like to choose a response most suitable for the client, because the client might not always be just a programmatic one, but could also be a user's browser, for example.

Therefore, we'd like to be able to say, for example:

- If a client accesses a URL that requires credentials, but none were supplied, the client is:
  a. Redirected to another URL if the client requested the e.g. `text/html` Content-Type.
  b. Returned an application/json response with error details if the `application/json` Content-Type was requested.
  c. Sending `WWW-Authenticate` if the URL includes `/foo` - see #119

It should be possible to set a behavior for all types of error codes (401, 403, 404, 500, ..).

**Additional context**

We believe this should be configurable globally as well as per rule. We could imagine a config layout such as:

```
strategy:
  401:
    - do: xml
      match:
        accept: ['application/xml']
    - do: json
      match:
        accept: ['application/json']
    - do: redirect
      match:
        accept: ['text/*']
        user-agent: ['*']
       # ...
       config:
         to: ...
# 403 ...
# 404 ...
```

Possible matchers discussed so far:

- HTTP Header `User-Agent`
- HTTP Header `Accept`
- Remote IP CIDR Match (should include `X-Forwarded-For`)

**Comment by Anaxilaus** [comment]
We may want to use some error handlers for specific audiences-for example developers- and define different configurations for different audiences to not expose information we don't want to.

We can define multiple strategies such as: 
<pre>
strategy:
  - for: <b>[network]</b>
    401:
      ...
  - for: <b>[network]</b>
    401: default
</pre>

**Comment by aeneasr** [comment]
That's a great idea, so maybe something like:

```
    - do: ...
      match:
        cidr: ['192.168.0.0/16']
       # ...
       # config:
```

?
