### ISSUE TITLE
Required field in schema (v0.32.1-beta.1)

### ISSUE THREAD

**Issue by Sbou** [ory/oathkeeper#303]
**Describe the bug**

With the latests version there is an validation error at startup.

> level=fatal msg="The configuration is invalid and could not be loaded." error="must validate one and only one schema (oneOf)" 
validation_error[0]="authorizers.keto_engine_acp_ory: Must validate one and only one schema (oneOf)" 
validation_error[1]="authorizers.keto_engine_acp_ory.config.required_action: required_action is required" 
validation_error[2]="authorizers.keto_engine_acp_ory.config.required_resource: required_resource is required" 

In my config file I have
```yaml   
authorizers:
      allow:
        enabled: true
      keto_engine_acp_ory:
        enabled: true
        config:
          base_url: "http://ketoserver/"
          subject: "{{ .Extra.subject }}"
```

And I have a rule with an authorizer:

```json
{
...
"authorizer": {
            "handler": "keto_engine_acp_ory",
                "config": {
                    "required_action": "permission:device:read",
                    "required_resource": "$2",
                    "flavor": "exact"
                }
        },
...
}
```

**Expected behavior**

The validation is done after that the global configuration and the rule are merged.
