### ISSUE TITLE
Decisions API works?

### ISSUE THREAD

**Issue by Dev-Force** [ory/oathkeeper#306]
Can't get the decisions when hitting the endpoint.
I also cant get decision prefix in url to work. The documentation is not clear enough or something is wrong with the api.

**Reproducing the bug**
Bring up the application and then:

curl -X GET http://localhost:4456/decisions -H 'Accept: application/json'

returns
{"error":{"code":404,"status":"Not Found","message":"Requested url does not match any rules"}}

rules.json
```
[
  {
    "id": "allow-anonymous-with-header-mutator",
    "upstream": {
      "url": "https://httpbin.org/anything/header"
    },
    "match": {
      "url": "http://<127.0.0.1|localhost>:4455/anything/header",
      "methods": [
        "GET"
      ]
    },
    "authenticators": [
      {
        "handler": "anonymous"
      }
    ],
    "authorizer": {
      "handler": "allow"
    },
    "mutators": [
      {
        "handler": "header",
        "config": {
          "headers": {
            "X-User": "{{ print .Subject }}"
          }
        }
      }
    ]
  },
  {
    "id": "deny-anonymous",
    "upstream": {
      "url": "https://httpbin.org/anything/deny"
    },
    "match": {
      "url": "http://<127.0.0.1|localhost>:4455/anything/deny",
      "methods": [
        "GET"
      ]
    },
    "authenticators": [
      {
        "handler": "anonymous"
      }
    ],
    "authorizer": {
      "handler": "deny"
    },
    "mutators": [
      {
        "handler": "noop"
      }
    ]
  },
  {
    "id": "allow-anonymous-with-id-token-mutator",
    "upstream": {
      "url": "https://httpbin.org/anything/id_token"
    },
    "match": {
      "url": "http://<127.0.0.1|localhost>:4455/anything/id_token",
      "methods": [
        "GET"
      ]
    },
    "authenticators": [
      {
        "handler": "anonymous"
      }
    ],
    "authorizer": {
      "handler": "allow"
    },
    "mutators": [
      {
        "handler": "id_token"
      }
    ]
  },
  {
    "id": "some-id",
    "upstream": {
      "url": "http://example.com/"
    },
    "match": {
      "url": "http://localhost:4456/my-service/whatever",
      "methods": [
        "GET"
      ]
    },
    "authenticators": [
      {
        "handler": "noop"
      }
    ],
    "authorizer": {
      "handler": "allow"
    },
    "credentials_issuer": {
      "handler": "noop"
    },
    "mutators": [
      {
        "handler": "noop"
      }
    ]
  }
]
```

docker-compose
```
oathkeeper:
    image: oryd/oathkeeper:latest
    volumes:
      - ./config.yaml:/config.yaml
      - ./rules.json:/rules.json
      - ./jwks.json:/jwks.json
    environment: 
      - DATABASE_URL=memory
      - ACCESS_RULES_REPOSITORIES=file:///rules.json
      - AUTHENTICATORS_ANONYMOUS_ENABLED=true
      - AUTHENTICATORS_NOOP_ENABLED=true
      - AUTHORIZERS_ALLOW_ENABLED=true
      - MUTATORS_NOOP_ENABLED=TRUE
      - MUTATORS_HEADER_ENABLED=true
      - LOG_LEVEL=trace
    ports:
      - 4456:4456
      - 4455:4455
```

**Expected behavior**

Excepted the endpoint to work.

**Environment**

- Version: oryd/oathkeeper:latest, v0.32.1, v0.32.1-beta.1
- Environment: macos, Docker
