### ISSUE TITLE
Bug in documentation 

### ISSUE THREAD

**Issue by vx3r** [ory/oathkeeper#309]
**Describe the bug**

There is a typo in oathkeeper documentation,  docker setup is showing 

```
oathkeeper                  | time="2019-12-12T07:42:19Z" level=fatal msg="The configuration is invalid and could not be loaded." error="additional property subject is not allowed" validation_error[0]="authenticators.anonymous: Additional property subject is not allowed"
```

In [configure-deploy#configure](https://www.ory.sh/docs/oathkeeper/configure-deploy#configure)

```
authenticators:
  anonymous:
    enabled: true
    subject: guest
``` 
Should be 
```
authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest
``` 
As described correctli in [authn#anonymous](https://www.ory.sh/docs/oathkeeper/pipeline/authn#anonymous)
