### ISSUE TITLE
Unable to set array config options via environment variables

### ISSUE THREAD

**Issue by cgearing** [ory/oathkeeper#342]
**Describe the bug**

There doesn't seem to be a way to provide the value for a configuration key that expects an array via an enrivonment variable.

**Reproducing the bug**

For example, with a docker-compose.yml like

```
  oathkeeper:
    image: oryd/oathkeeper
    ports:
      - "127.0.0.1:8091:4455"
    volumes:
      - ./ory/rules.yml:/ory/rules/rules.yml
    environment:
      SERVE_API_PORT: 4456
      SERVE_API_HOST: ""
      SERVE_PROXY_PORT: 4455
      SERVE_PROXY_HOST: ""
      LOG_LEVEL: debug
      AUTHENTICATORS_JWT_ENABLED: "true"
      MUTATORS_HEADER_ENABLED: "true"
      AUTHORIZERS_ALLOW_ENABLED: "true"
      AUTHENTICATORS_NOOP_ENABLED: "true"
      ACCESS_RULES_REPOSITORIES: "file://ory/rules/rules.yml"
      SERVE_API_CORS_ENABLED: "true"
      SERVE_API_CORS_ALLOWED_HEADERS: "['Access-Control-Allow-Origin','Authorization']"
      CORS_ALLOWED_ORIGINS: "*"
      SERVE_API_CORS_DEBUG: "true"
```

the following error would be produced.

*Server logs*
```
oathkeeper_1              | time="2020-01-20T10:59:15Z" level=warning msg="No config file was defined and no file was found in $HOME/.oathkeeper.yaml" error="Config File \".oathkeeper\" Not Found in \"[/]\""
oathkeeper_1              | time="2020-01-20T10:59:15Z" level=fatal msg="The configuration is invalid and could not be loaded." error="invalid type. Expected: array, given: string" validation_error[0]="serve.api.cors.allowed_headers: Invalid type. Expected: array, given: string"
```

**Expected behavior**

Some clear instructions of how to provide an array of values to these keys would be really helpful.  Alternatively, if it's not possible to parse these from environment variables, a little note in the docs would be great :)

**Environment**

* Version: ORY Oathkeeper v0.35.1-beta.1+oryOS.15
* Environment: Docker with Docker-Compose
