### ISSUE TITLE
High latencies

### ISSUE THREAD

**Issue by ecktom** [ory/oathkeeper#346]
**Describe the bug**

Started using Oathkeeper and was quiet surprised about it's somewhat high latencies. I'm using a simple forward rule including (AllowAuthorizer / NoopAuthenticator / NoopMutator) 

```yaml
    - id: some-rule
      match:
        url: http://some-url/api/<.*>
        methods:
        - POST
        - GET
        - PATCH
        - PUT
      authenticators:
      - handler: noop
        config: {}
      authorizer:
        handler: allow
        config: {}
      mutators:
      - handler: noop
        config: {}
```

It takes around ~80ms for a request getting processed. I did some cpu profiling to check what happens. Turns out that https://github.com/ory/oathkeeper/blame/master/driver/configuration/provider_viper.go#L200 is getting called for every request multiplied with each authenticator, authorizer and mutator. This is calling the viper stack to compute the config which then get validated against the schema.

I just did some basic 3 line's caching there to proof my point and brought it down to ~5ms immediately (with all the schema validation still in place)

*CPU profile*

![pprof001](https://user-images.githubusercontent.com/3372410/72887202-83007000-3d0b-11ea-9bcf-2bda7133f894.png)

*Server configuration*
```yaml
    log:
      level: debug
      format: json
    profiling: cpu
    access_rules:
      repositories:
      - file:///etc/oathkeeper/rules.yaml
    authenticators:
      jwt:
        enabled: true
        config:
          jwks_urls:
          - https://some-url/jwks.json
      noop:
        enabled: true
        config: {}
    authorizers:
      allow:
        enabled: true
        config: {}
      deny:
        enabled: true
        config: {}
      keto_engine_acp_ory:
        enabled: true
        config:
          base_url: http://keto-url:4466/
          required_action: ""
          required_resource: ""
    mutators:
      noop:
        enabled: true
        config: {}
      header:
        enabled: true
        config:
          headers:
            X-SOME-HEADER: '{{ print .Subject }}'
```
**Expected behavior**

Would have expected some kind of caching here ;) I like the Prometheus approach where you would habe to call an api endpoint in order to reload the config.

**Environment**

* Version: v0.35.1
* Environment: Docker -> K8s
