### ISSUE TITLE
Can't override `authenticators.oauth2_introspection.config.from_token` value from config file in API Access Rules file

### ISSUE THREAD

**Issue by samuellaycock** [ory/oathkeeper#359]
**Describe the bug**

When overriding the `from_token` config option for the `oauth2_introspection` authenitcator, setting a new `from_token` value in your API Access Rule definitions causes Oathkeeper to report: "authenticator matching this route is misconfigured or disabled"

**Reproducing the bug**

1. Create a `.oathkeeper.yml` file that defines the `oauth2_introspection` authenitcator as enabled and looking for a `header` in the `from_token` field of `config`.
2. In your API Access Rule definitions, set a route to use the `oauth2_introspection` authenticator but set a new `from_token` value in the `config`, e.g. `query_parameter`

*Server logs*

```
{"error":"authenticator matching this route is misconfigured or disabled","level":"error","msg":"A rule uses a malformed configuration and all URLs matching this rule will not work. You should resolve this issue now.","time":"2020-02-12T12:57:04Z"}
```

*Server configuration*

`.oathkeeper.yml`:

```yaml
...
oauth2_introspection:
    enabled: true
    config:
      introspection_url: http://localhost:4445/oauth2/introspect
      token_from:
        header: X-Some-Token
...
```

`.access_rules.yml`:

```yaml
...
authenticators:
    - handler: oauth2_introspection
      config:
        from_token:
          query_parameter: x_some_token
...
```

**Expected behavior**

According to the [documentation](https://www.ory.sh/docs/oathkeeper/api-access-rules): "The configuration can be defined globally as well as per Access Rule. The configuration from the Access Rule is overrides values from the global configuration."

I would expect the above configuration to be valid and for that route to be authenticated using the defined query parameter instead of the global header configuration. 

**Environment**

* Docker Image: oryd/oathkeeper:v0.35.5-alpine

**Comment by aeneasr** [comment]
Typo in `token_from` and `from_token`

**Comment by samuellaycock** [comment]
Whoops. Sorry, thanks!

**Comment by samuellaycock** [comment]
No sorry, still getting the same issue, just a bad copy paste from me before.

**Comment by aeneasr** [comment]
Please post the full config and even better, a reproducible test case.

**Comment by aeneasr** [comment]
Closing due to inactivity

**Comment by uttaravadina** [comment]
@aeneasr I am having the same issue when using a rules.json with config.yaml

**ERROR:**
```
**ERRO**[2020-06-16T18:56:36Z] A Rule uses a malformed configuration and all URLs matching this rule will not work. 
You should resolve this issue now.  **audience**=application **error**=map[debug: message:authenticator matching this route is disabled 
reason:Authenticator "oauth2_introspection" is disabled per configuration. status:Internal Server Error status_code:500] **rule_id**=test **service_name**=ORY Oathkeeper service_version=

```


*config.yaml*
```
serve:
  proxy:
    port: 4455 # run the proxy at port 4455
  api:
    port: 4456 # run the api at port 4456
  prometheus:
    port: 9090

access_rules:
  repositories:
    - file:///home/mc-user/ok-iap/rules.json

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
	verbose: true
    redirect:
      enabled: false
```

*rules.json*

```
[{
  "id": "test",
  "upstream": {
    "url": "http://localhost:7111/test"
  },
  "match": {
    "url": "https://exmaple.com/test",
    "methods": [
      "POST"
    ]
  },
  "authenticators": [{
    "enabled": true,
    "handler": "oauth2_introspection",
    "oauth2_introspection": {
      "enabled": true
    },
    "config": {
      "introspection_url": "http://localhost:4445/oauth2/introspect",
      "token_from": {
        "header": "Authorization"
      },
      "required_scope": ["openid", "offline_access"],
      "cache" : {
        "enabled": true,
        "ttl": "10s"
      }
    }
  }],
  "authorizer": {
    "handler": "allow",
    "enabled": true
  },
  "mutators": [
    {
      "handler": "header",
      "enabled": true,
      "config": {
        "headers": {
          "X-User": "{{ print .Subject }}",
          "X-User-Data": "{{ print .Extra }}"
        }
      }
    }
  ]
}]
```
