### ISSUE TITLE
Hierarchic scope strategy not working for OAuth2 Introspection authn

### ISSUE THREAD

**Issue by tleef** [ory/oathkeeper#377]
**Describe the bug**

I'm running into an issue authenticating a request with oathkeeper using the hierarchic scope strategy. 
I'm trying to lock down my hydra introspection endpoint.

I have added the following to the oathkeeper config to enable the oauth2 introspection authenticator
```
authenticators:
  oauth2_introspection:
    enabled: true
    config:
      introspection_url: http://localhost:4445/oauth2/introspect
      scope_strategy: hierarchic
      introspection_request_headers:
        x-forwarded-proto: https
```

I have added the following rule to protect my hydra introspection endpoint
```
- id: admin:introspect-access-token
  upstream:
    url: http://localhost:4445
    preserve_host: true
    strip_path: /v1/op
  match:
    url: http://<[a-zA-Z0-9-_:\.]+>/v1/op/oauth2/introspect
    methods:
      - POST
  authenticators:
    - handler: oauth2_introspection
      config:
        required_scope:
          - admin.introspect
  authorizer:
    handler: allow
  mutators:
    - handler: noop
```

I have created the following client for administrative purposes
```
{
    "client_id": "090e30ed-bc4b-478d-bb82-975a1667334b",
    "client_name": "Admin",
    "redirect_uris": [],
    "grant_types": [
        "client_credentials"
    ],
    "response_types": [],
    "scope": "admin",
    "audience": [],
    "owner": "",
    "policy_uri": "",
    "allowed_cors_origins": [],
    "tos_uri": "",
    "client_uri": "",
    "logo_uri": "",
    "contacts": [],
    "client_secret_expires_at": 0,
    "subject_type": "public",
    "token_endpoint_auth_method": "client_secret_basic",
    "userinfo_signed_response_alg": "none",
    "created_at": "2020-03-10T13:43:55Z",
    "updated_at": "2020-03-10T13:43:55Z",
    "metadata": null
}
```

Using that client I have obtained the following token.
```
VRS1H90d3XeP5xX18EeiIG31RHvU-1ewUzcGRLHwT1U.DBqrTNGO0d5h4s8Jn6-3sBGsYvQsL87hjy6PvZDD3Co
```

I then attempted to introspect that token with the following request (Format from insomnia timeline)
```
> POST /v1/op/oauth2/introspect HTTP/2
> Host: myapp.com
> User-Agent: insomnia/7.1.1
> Content-Type: application/x-www-form-urlencoded
> Authorization: Bearer VRS1H90d3XeP5xX18EeiIG31RHvU-1ewUzcGRLHwT1U.DBqrTNGO0d5h4s8Jn6-3sBGsYvQsL87hjy6PvZDD3Co
> Accept: */*
> Content-Length: 93

| token=VRS1H90d3XeP5xX18EeiIG31RHvU-1ewUzcGRLHwT1U.DBqrTNGO0d5h4s8Jn6-3sBGsYvQsL87hjy6PvZDD3Co
```

oathkeeper, which is protecting the introspection endpoint, responded with the following
```
{
  "error": {
    "code": 401,
    "status": "Unauthorized",
    "request": "bec3fc5f-2569-92ed-8ae7-3925cc3677a0",
    "reason": "Access token i says token is not active",
    "message": "Access credentials are invalid"
  }
}
```

I then inspected the same token again but this time using a different Authorization token which has the scope of `admin.introspect`.
```
> POST /v1/op/oauth2/introspect HTTP/2
> Host: myapp.com
> User-Agent: insomnia/7.1.1
> Content-Type: application/x-www-form-urlencoded
> Authorization: Bearer XPx_x65ReH10Di-HALA62l9TYAQJPZth4t7e7apYMSc.jHVDuDLOqyt9sd6gHQ5Gw2WYlCq7oAk0CBLkbaTgX9M
> Accept: */*
> Content-Length: 93

| token=VRS1H90d3XeP5xX18EeiIG31RHvU-1ewUzcGRLHwT1U.DBqrTNGO0d5h4s8Jn6-3sBGsYvQsL87hjy6PvZDD3Co
```

This time the request to was successful and I received the following response.
```
{
  "active": true,
  "scope": "admin",
  "client_id": "090e30ed-bc4b-478d-bb82-975a1667334b",
  "sub": "090e30ed-bc4b-478d-bb82-975a1667334b",
  "exp": 1583860409,
  "iat": 1583856809,
  "iss": "https://myapp.com/v1/op/",
  "token_type": "access_token"
}
```

As you can see the introspected token is active and has the `admin` scope. The `admin` scope *should* match `admin.introspect` using the hierarchic scope strategy.

I investigated a little further and found that oathkeeper is sending the required_scope to hydra when inspecting the token.
https://github.com/ory/oathkeeper/blob/master/pipeline/authn/authenticator_oauth2_introspection.go#L88

Since `admin.introspect`, the required scope, doesn't equal `admin`, the granted scope, hydra responds with the following when introspecting the token
```
{
  "active": false
}
```

Oathkeeper sees this response and rejects the request.

It seems the me that the solution is for oathkeeper to not include the scope when introspecting the token and instead validate the scope itself (which it already does further down)
https://github.com/ory/oathkeeper/blob/master/pipeline/authn/authenticator_oauth2_introspection.go#L132-L138

**Environment**

* Version: 
- Oathkeeper: oryd/oathkeeper:v0.33.0-beta.1
- Hydra: oryd/hydra:v1.1.0-alpine
* Environment: Docker
