### ISSUE TITLE
Feature: Support JWT revokation though http validation

### ISSUE THREAD

**Issue by Cohedrin** [ory/oathkeeper#421]
**Is your feature request related to a problem? Please describe.**

Currently, oathkeeper does not seem to support revoking a JWT. JWTs are great in that they don't need an online check to make sure that the user is authenticated, but because of this, they don't have a built in mechanism for revocation. 

This means if a user's token is comprised, the attacker can continue to use the token to act as the user until the token expires. In some cases this may not matter, but in other cases this could have serious consequences.

**Describe the solution you'd like**

A common solution to this problem is to implement a blacklist/whitelist. This keeps most of the advantages of JWTs while adding in the ability to revoke tokens and have them reflected instantly. 

I would imagine some (most?) users would not like this functionality, as it does reintroduce a database layer in a auth system that otherwise does not require one. However, I believe we can leave that up to the individual users by making this a configurable option. 

For example:
```yml
authenticators:
  jwt:
    # Set enabled to true if the authenticator should be enabled and false to disable the authenticator. Defaults to false.
    enabled: true

    config:
      ...
      validation_urls:
        - https://my-website.com/validate
```
By making this an http endpoint, the user is free to put whatever service they would like here, for example a small go server that checks the token against a global redis database.

**Describe alternatives you've considered**
Alternatives include:
- Adding adapters for individual stores (postgres, redis, mysql, etc)
  - This is suboptimal as it requires oathkeeper having drivers and custom implementations for all the possible stores a user might want
  - Likely not worth ongoing maintenance effort for a feature that only some users will be using.
- Keep the status quo 
  - The status quo is not broken, it simply provides less functionality to the users and removes some ability from them to make choices to their specific domain.
  - In most cases this implementation of a jwt check probably works fine, but I can definitely imagine some scenarios where it does not.

**Additional context**
I'd be happy to add in this functionality myself if this would be an acceptable change!
