### ISSUE TITLE
Hydrator cache should also have `enabled` for consistency

### ISSUE THREAD

**Issue by aeneasr** [ory/oathkeeper#431]
**Is your feature request related to a problem? Please describe.**

The hydrator cache currently does not use an `enabled` config flag (like e.g. oauth2_introspection) to mark the cache as en or disabled:

```
mutators:
  hydrator:
    config:
      cache:
        ttl: 1h # setting this enables the cache
```

**Describe the solution you'd like**

```
mutators:
  hydrator:
    config:
      cache:
        enabled: true
        # ttl should default to something
```
