### ISSUE TITLE
Incorrect report of timeout when reading JWKS?

### ISSUE THREAD

**Issue by catper** [ory/oathkeeper#436]
**Describe the bug**

Oathkeeper returns 403 with the message "Ignoring JSON Web Keys from at least one URI because the request timed out waiting for a response." but we have reason to believe that this is in fact not correct.

To try to understand what is happening, we've forked the repo and added a bunch of debug prints and as far as it is possible to see, the file containing the JWKS is in fact read without issues. Since the JWKS file is mounted in to the container a timeout also seems highly unlikely.

We get to the end of `resolve` in `fetcher_default.go` without issues and a print at that point indicates that `s.keys[location.String()] ` is well defined. Furthermore, there is no difference between the prints when Oathkeeper returns 200 compared to when it returns 403.

We've tried to increase the timeout for the context but that doesn't seem to make a difference. 

**Reproducing the bug**

Deploy Oathkeeper through the official Helm chart with the Oathkeeper image set to v0.37.1-alpine. 

Global id_token config:
```
      id_token:
        enabled: true
        config:
          issuer_url: http://noop
          jwks_url: file:///noop
          ttl: 60s
```

Access rule:
```
        "mutators": [
            {
                "handler": "id_token",
                "config": {
                    "issuer_url": "https://oathkeeper-api.svc.cluster.local",
                    "jwks_url": "file:///etc/secrets/mutator.id_token.jwks.json"
                }
            }
        ]
```

Create a token with Hydra and then immediately pass said token on to the Oathkeeper decisions API through any request. Oathkeeper more often than not responds with 

time="2020-05-13T10:09:12Z" level=error msg="Ignoring JSON Web Keys from at least one URI because the request timed out waiting for a response."
time="2020-05-13T10:09:12Z" level=warning msg="The mutation handler encountered an error" error="An internal server error occurred, please contact the system administrator" granted=false http_host=*** http_method=POST http_url="***" http_user_agent= mutation_handler=id_token reason_id=mutation_handler_error rule_id=authenticate subject=test-client
time="2020-05-13T10:09:12Z" level=warning msg="Access request denied" error="An internal server error occurred, please contact the system administrator" granted=false http_host=*** http_method=POST http_url="***" http_user_agent=

_Server logs_
See above

_Server configuration_
See above

**Expected behavior**

Oathkeeper consistenly returns 200.

**Environment**

Oathkeeper v0.37.1_alpine
AWS cluster running Kubernetes v1.14

**Additional context**

Unfortunately, my golang skills are very limited so it's hard for me to debug this but I wonder if there might be some sort of concurrency issue happening here? Any feedback would be appreciated.

**Comment by catper** [comment]
So just to see what happens I tried commenting out `case <-ctx.Done():` in `fetchParallel` and token signing then runs through without errors so the JWKS definitely does get read properly.

As stated, go is not my language and I'm not sure I fully understand how `ctx.Done()` works but after reading [this](https://tour.golang.org/concurrency/5) I wonder if it's possible for both cases to be valid at once, leaving the one resulting in an error to get chosen at random?

**Comment by aeneasr** [comment]
Did you define any remote URL for the JWKS URLs? If not, this is indeed a bug / should be investigated.

**Comment by catper** [comment]
the jwks urls are specified as a single a file path, which is mounted into the container through a secret, at startup.

the problem here is that we are running oathkeeper in a somewhat non-direct fashion, namely through an envoy authz filter in istio and i think that's where the root of the evil lies. when specifying the authz filter, you give a timeout for the communication between envoy and oathkeeper and after a lot of back and forth we concluded that it is in fact this timeout that is causing the issues. when the timeout is reached the "global" context is cancelled, which means that all contexts that it in turn has given rise to are cancelled as well and hence oathkeeper returns an error. as the timeout set is very generous it took us a while to realise that that might be the issue but everything is definitely pointing in that direction.

in this particular context the error returned by oathkeeper is in my opinion misleading since the problem isn't actually anything to do with the fetching of the jwks but rather that the entire request evaluation takes too long in the eyes of the caller. i'm not sure that there's an easy way to capture and communicate that to the end user though?

**Comment by aeneasr** [comment]
Hm, I'm not sure it's hard to say without a reproducible case. If you could provide one I'd be able to debug it. Do you mean that envoy is the one timing out?

> in this particular context the error returned by oathkeeper is in my opinion misleading since the problem isn't actually anything to do with the fetching of the jwks but rather that the entire request evaluation takes too long in the eyes of the caller. i'm not sure that there's an easy way to capture and communicate that to the end user though?

Yes, I think the first step would be to use `LOG_LEVEL=trace`. That will hopefully help a bit!

**Comment by catper** [comment]
since it's kind of a big setup it's a bit difficult to provide a complete example but in short:

- install istio v 1.5.1 on a kubernetes cluster, through istio operator
- deploy oathkeeper in the same cluster
- apply an authz filter that looks something like this:

```
metadata:
  name: oathkeeper-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.ext_authz
        config:
          http_service:
            server_uri:
              uri: "http://oathkeeper-api.default.svc.cluster.local"
              cluster: outbound|4456||oathkeeper-api.default.svc.cluster.local 
              timeout: 0.25s
            path_prefix: /decisions
            authorization_response:
              allowed_upstream_headers:
                patterns:
                  - exact: "authorization"
```

oathkeeper needs to be configured to use the `oauth2_introspection` and `oauth2_client_credentials` authenticators, `allow` authorizer and the `id_token` mutator. 

if the overall request evaluation takes more than the timeout specified in the envoy filter (in this case 0.25s) the request will be cancelled and it doesn't matter if it should be approved or not. to try to verify this we commented out `ctx.Done()` in `fetcher_default` and indeed saw that even though oathkeeper eventually logged `200, request granted`, we got a 403 back from the filter. the evaluation time logger by oathkeeper in this context was generally in the region of 300 ms and so well above the allotted 0.25s for the request roundtrip.

0.25s is a long time and you think it'd be more than enough but since we have restrictions on our clusters forcing us to run hydra in a different region than oathkeeper the introspection/token generation takes a long time and that is most likely why everything goes south but we can hardly blame oathkeeper for that!
