### ISSUE TITLE
Allow mulitple authenticators to work on same header

### ISSUE THREAD

**Issue by pike1212** [ory/oathkeeper#466]
**Is your feature request related to a problem? Please describe.**

I would like clients to be able to call my service using either OAuth tokens or JWTs and the same header ("Authorization"). Currently, if the first one fails, the next one is never tried.

**Describe the solution you'd like**

Maybe a flag in one of the authenticators that tells it not to error if it can't validate the token?

**Comment by aeneasr** [comment]
Yeah that sounds like a reasonable request. I'm not sure how we could address this properly. What we really need is an AND and OR logic I guess? That will be quite horrific to define in YAML though...

IMO this should be a part of https://github.com/ory/oathkeeper/issues/441

**Comment by pike1212** [comment]
What is time frame for next gen? We are currently running a custom branch to enable this functionality

**Comment by a-candiotti-pvotal** [comment]
We have a similar situation.

We are attributing rights and restricting access based on audiences, which lead us to have several JWT authenticators in our configuration.

The current implementation considers that if a token does not match a JWT authenticator's audiences, the authenticator should return an Unauthorized.
Which does not work in our case

Consider the following example:
```
authenticators:
  - config:
      allowed_algorithms:
        - RS256
      jwks_urls:
        - 'https://trusted.com/jwks.json'
      required_scope:
        - scope1
      target_audience:
        - 'https://audience1.com'
      trusted_issuers:
        - 'https://auth.com/'
    handler: jwt
  - config:
      allowed_algorithms:
        - RS256
      jwks_urls:
        - 'https://anothertrusteddomain.com/jwks.json'
      required_scope:
        - scope1
      target_audience:
        - 'https://audience2.com'
      trusted_issuers:
        - 'https://auth.com/'
    handler: jwt

```

For a JWT that has the 'https://audience2.com' audience, here is the behavior we thought would occur:
- the first authenticator refuses the token but passes the responsability to the second authenticator
- the second one accepts the token
  
What happened instead:
  - the first authenticator refused the token as the audiences didn't match.
  
A flag in the config would indeed be a nice way to make an exception in the authenticator chain.
