### ISSUE TITLE
config_key=mutators.hydrator.config="doesn't validate with #/definitions/configMutatorsHydrator when hydrate mutator enabled in access-rule

### ISSUE THREAD

**Issue by ajmckee** [ory/oathkeeper#483]
**Describe the bug**

When configuring an access rule with a hydrator, the hydrator must also be defined within the server config in complete rather than hydrator.enabled = true. 

**Reproducing the bug**

1. Add the hydrator.enabled = true key to the service config. 
```yaml
hydrator:
    enabled: true
```
2. Add a mutator rule within access-rules.json|yaml 
```yaml
mutators:
    - handler: hydrator
      config:
        api:
          url: http://localhost:3002/
        cache:
          ttl: 60s
```

Service will complain of the following;

**config_key=mutators.hydrator.config]="doesn't validate with \"#/definitions/configMutatorsHydrator**

To address the issue the following configuration would have to be applied;

1. server.yaml
```yaml
mutators:
  noop:
    enabled: true
  header:
    enabled: false
  hydrator:
    enabled: true
    config:
      api:
        url: http://localhost:3002/
      cache:
        ttl: 180s
```
2. access-rules.yaml
```yaml
mutators:
    - handler: hydrator
      config:
        api:
          url: http://localhost:3002/
        cache:
          ttl: 60s
```

_Server logs_

```
oathkeeper serve -c config.yaml
INFO[0000] Config file loaded successfully.              path=config.yaml
FATA[0000] The configuration is invalid and could not be loaded.  [config_key=mutators.hydrator.config]="doesn't validate with \"#/definitions/configMutatorsHydrator\"" [config_key=mutators.hydrator.enabled]="value must be false" [config_key=mutators.hydrator]="oneOf failed" config_file=config.yaml
```

_Server configuration_

```yaml
access_rules:
  repositories:
    - file://./access-rules.yaml
authenticators:
  anonymous:
    enabled: true
    config:
      subject: anonymous
  noop:
    enabled: true
  unauthorized:
    enabled: true
  oauth2_introspection:
    enabled: true
    config:
      introspection_url: https://hydra-admin/oauth2/introspect
  oauth2_client_credentials:
    enabled: true
    config:
      token_url: https://hydra/oauth2/token
authorizers:
  allow:
    enabled: true
  deny:
    enabled: true
mutators:
  noop:
    enabled: true
  header:
    enabled: false
  hydrator:
    enabled: true
  id_token:
    enabled: true
    config:
      issuer_url: https://hydra/
      jwks_url: file://./jwks.json
      ttl: 60s
      claims:
        '{"aud": ["test_ui_dev"],"def": {{ .Extra | toJson }} }'
log:
  level: debug
  format: text
serve:
  proxy:
    cors:
      enabled: true
      allow_credentials: true
      allowed_headers:
        - Authorization
        - Content-Type
      allowed_origins:
        - http://localhost:8080
        - http://localhost:8081
        - http://localhost:3000
        - http://localhost:3001
profiling: mem
---
# Sample Access Rule
- id: test-api-core
  upstream:
    url: http://localhost:3001
    preserve_host: true
  match:
    url: http://localhost:<[[:digit:]]+>/<(?!webhooks).*>
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
  authenticators:
    - handler: oauth2_introspection
      config:
        introspection_url: https://admin-hydra/oauth2/introspect
        scope_strategy: wildcard
  authorizer:
    handler: allow
  mutators:
    - handler: hydrator
      config:
        api:
          url: http://localhost:3002/
        cache:
          ttl: 60s
    - handler: id_token
  errors:
  - handler: json
```

**Expected behavior**

Global hydrator should not have to be defined as docs state;

"It works by making an upstream HTTP call to an API specified in the Per-Rule Configuration section below."

**Environment**
- Version:    v0.38.2-beta.1
- Git Hash:   0de2682a1e0d556688c48db52ccc4e24f2bce336
- Build Time: 2020-05-25T10:34:00Z
- Environment: Linux, MacOs
