### ISSUE TITLE
oauth2_introspection not parsing single string aud valie

### ISSUE THREAD

**Issue by stevepnbscott** [ory/oathkeeper#491]
**Describe the bug**

I have configured oathkeeper to use an authenticator for oauth2_introspection using keycloak.

By default keycloak returns only a single value in the aud claim of the token;

```
{
    "exp": 1596123440,
    "nbf": 0,
    "iat": 1596123140,
    "jti": "57f536d3-2b17-4652-9859-c58a8f4c77a7",
    "aud": "account",
    "typ": "Bearer",
    "acr": "1",
    "active": true
}
```

According to the RFC  this is valid : 

> _aud
>
>      OPTIONAL.  Service-specific string identifier or list of string
>      identifiers representing the intended audience for this token, as
>      defined in JWT [RFC7519]._

However I see Oathkeeper unable to parse that return value; 

```
**_time=2020-07-30T14:27:31Z level=error msg=An error occurred while handling a request code=500 debug= details=map[] error=json: cannot unmarshal string into Go struct field AuthenticatorOAuth2IntrospectionResult.aud of type []string reason= request-id= status=500 writer=JSON_*
```

**Reproducing the bug**

using simple docker file : 

```
FROM oryd/oathkeeper:latest1

ADD config.yaml /config.yaml
ADD rules.json /rules.json
ADD jwks.json /jwks.json
```

1. Run oathkeeper locally;

```
$ docker build -t ory-oathkeeper-demo .

# Docker run with mapping to config with rules/jwsk etc locally
docker run --rm \
  --name ory-oathkeeper-demo \
  -v ~/Oathkeeper:/configs \
  -p 4455:4455 \
  -p 4456:4456 \
  ory-oathkeeper-demo \
  --config /configs/config.yaml \
  serve
```

2. Call the API to trigger the introspeciton

```
$ curl -X GET -H 'Authorization: Bearer <token here>' http://127.0.0.1:4455/auth/intro
```

_Server logs_

```
time=2020-07-30T14:27:31Z level=info msg=started handling request http_request=map[headers:map[accept:*/* authorization:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". user-agent:curl/7.54.0] host:127.0.0.1:4455 method:GET path:/auth/intro query:<nil> remote:172.17.0.1:56148 scheme:http]
time=2020-07-30T14:27:31Z level=warning msg=The authentication handler encountered an error audience=application authentication_handler=oauth2_introspection error=map[message:json: cannot unmarshal string into Go struct field AuthenticatorOAuth2IntrospectionResult.aud of type []string] granted=false http_host=127.0.0.1:4455 http_method=GET http_url=http://127.0.0.1:4455/auth/intro http_user_agent=curl/7.54.0 reason_id=authentication_handler_error rule_id=oauth-introspection service_name=ORY Oathkeeper service_version=v0.38.3-beta.1
time=2020-07-30T14:27:31Z level=warning msg=Access request denied audience=application error=map[message:json: cannot unmarshal string into Go struct field AuthenticatorOAuth2IntrospectionResult.aud of type []string] granted=false http_host=127.0.0.1:4455 http_method=GET http_url=http://127.0.0.1:4455/auth/intro http_user_agent=curl/7.54.0 service_name=ORY Oathkeeper service_version=v0.38.3-beta.1
time=2020-07-30T14:27:31Z level=error msg=An error occurred while handling a request code=500 debug= details=map[] error=json: cannot unmarshal string into Go struct field AuthenticatorOAuth2IntrospectionResult.aud of type []string reason= request-id= status=500 writer=JSON
time=2020-07-30T14:27:31Z level=info msg=completed handling request http_request=map[headers:map[accept:*/* authorization:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". user-agent:curl/7.54.0] host:127.0.0.1:4455 method:GET path:/auth/intro query:<nil> remote:172.17.0.1:56148 scheme:http] http_response=map[status:500 text_status:Internal Server Error took:89.3933ms]
```

_Server configuration_

Config 

```yaml
serve:
  proxy:
    port: 4455 # run the proxy at port 4455
  api:
    port: 4456 # run the api at port 4456

access_rules:
  repositories:
    - file:///configs/rules.json

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: https://www.ory.sh/docs

mutators:
  header:
    enabled: true
    config:
      headers:
        X-User: "{{ print .Subject }}"
        # You could add some other headers, for example with data from the
        # session.
        # X-Some-Arbitrary-Data: "{{ print .Extra.some.arbitrary.data }}"
  noop:
    enabled: true
  id_token:
    enabled: true
    config:
      issuer_url: http://localhost:4455/
      jwks_url: file:///configs/jwks.json

authorizers:
  allow:
    enabled: true
  deny:
    enabled: true

authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest
#
# OAUTH 2.0 Client Credentials
#
  oauth2_client_credentials:
    enabled: true
    config:
      token_url: http://x.x.x.x:8080/auth/realms/Developer/protocol/openid-connect/token

#
# OAUTH 2.0 Token Introspection
#
  oauth2_introspection:
    enabled: true

    config:
      introspection_url: http://x.x.x.x:8080/auth/realms/Developer/protocol/openid-connect/token/introspect
      scope_strategy: exact
#      required_scope:
#        - email
#        - profile
      pre_authorization:
        enabled: false
        client_id: Client-Credentials-App
        client_secret: xxx
#        scope:
#          - email
        token_url: http://x.x.x.x:8080/auth/realms/Developer/protocol/openid-connect/token
      token_from:
        header: Authorization
        # or
        # query_parameter: auth-token
        # or
        # cookie: auth-token
      introspection_request_headers:
        x-forwarded-proto: http

      cache:
        enabled: true
        ttl: 60s

  jwt:
    # Set enabled to true if the authenticator should be enabled and false to disable the authenticator. Defaults to false.
    enabled: true

    config:
      jwks_urls:
        - http://x.x.x.x:8080/auth/realms/Developer/protocol/openid-connect/certs
      scope_strategy: exact
#      required_scope:
#        - profile
#        - email
#      target_audience:
#        - account 
      trusted_issuers:
        - http://x.x.x.x:8080/auth/realms/Developer
      allowed_algorithms:
        - RS256
      token_from:
        header: Authorization
        # or
        # query_parameter: auth-token
        # or
        # cookie: auth-token
log:
  
  ## Level ##
  #
  # Debug enables stack traces on errors. Can also be set using environment variable LOG_LEVEL.
  #
  # Default value: info
  #
  # Set this value using environment variables on
  # - Linux/macOS:
  #    $ export LOG_LEVEL=<value>
  # - Windows Command Line (CMD):
  #    > set LOG_LEVEL=<value>
  #
  level: debug
```

Rules 

```json
 {
    "id": "oauth-introspection",
    "upstream": {
      "url": "https://httpbin.org/anything/header"
    },
    "match": {
      "url": "http://<127.0.0.1|localhost>:4455/auth/intro",
      "methods": [
        "GET"
      ]
    },
    "authenticators": [{
      "handler": "oauth2_introspection",
      "config": {
        "required_scope": ["profile", "email"],
        "introspection_request_headers": {          
          "Authorization": "Basic <auth here>",
          "token_type_hint": "requesting_party_token"
         }
      }
    }],
    "authorizer": { "handler": "allow" },
    "mutators": [{ "handler": "noop" }]
  }
```

**Expected behavior**

I expect the authenticator to parse the token introspeciton response content and evaluate validity of the token and the scopes.

**Environment**

Oathkeeper docker : ORY Oathkeeper service_version=v0.38.3-beta.1

running Docker on Mac: 

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
- Environment: Debian, Docker, ...

**Additional context**

If I update Keycloak and add in additional fields into the aud field, to ensure an array is returned all works fine.
