### ISSUE TITLE
oauth2_introspection

### ISSUE THREAD

**Issue by llorllale** [ory/oathkeeper#597]
**Describe the bug**

The `oauth2_introspection` authenticator expects the oauth2 access_token to be in plain form in the `Authorization` header. In contrast, [OAuth2 Bearer Token Usage](https://tools.ietf.org/html/rfc6750#section-2.1) specifies the token should be base64-encoded in the header (similar to the HTTP basic authorization scheme).

**Reproducing the bug**

1. Enable the `oauth2_introspection` authenticator in the global config:
```yaml
authenticators:
  oauth2_introspection:
    enabled: true
    config:
      introspection_url: https://hydra.example.org:4445/oauth2/introspect
```
2. Enable the authenticator in an access rule
3. Invoke the HTTP endpoint with the access rule. Construct the `Authorization` header as per [RFC6750](https://tools.ietf.org/html/rfc6750#section-2.1).

**Expected behavior**

Given a valid access_token, the request should be authorized.

**Environment**

- Version: v0.38.4-alpine
- Environment: alpine

**Additional context**

The issue can be worked around by sending the access_token in plain form.
