### ISSUE TITLE
noop authenticator doesn't skip id_token mutator

### ISSUE THREAD

**Issue by lcsanchez** [ory/oathkeeper#669]
**Describe the bug**

Using the `noop` authenticator doesn't behave as describe by the [authn pipeline docs](https://www.ory.sh/oathkeeper/docs/pipeline/authn#noop).

> The noop handler tells ORY Oathkeeper to bypass authentication, authorization, and mutation

When I make a request that matches the rule below, the `id_token` mutator being invoked and a JWT token with `sub: ""` is injected into the `Authorization` header.

**Reproducing the bug**

_Server configuration_

```yaml
access_rules:
  repositories:
    - file://config/access-rules.json

authorizers:
  allow:
    enabled: true
  deny:
    enabled: true

authenticators:
  noop:
    enabled: true
  oauth2_introspection:
    enabled: true
    config:
      introspection_url: https://hydra-admin.local/oauth2/introspect

mutators:
  noop:
    enabled: true
  id_token:
    enabled: true
    config:
      issuer_url: http://oathkeeper.local/
      jwks_url: file://config/secret.jwks
```

```json
[{
  ...
  "authenticators": [
    {
      "handler": "oauth2_introspection",
      "config": {
        "required_scope": []
      }
    },
    { 
      "handler": "noop" 
    }
  ],
  "authorizer": { "handler": "allow" },
  "mutators": [{ "handler": "id_token" }],
  "errors": [{ "handler": "json" }]
}]

```

**Expected behavior**

I would expect that when a request is made that matches the rule and no `Authorization` header is specified, the request is forwarded with no `Authorization` header value present.

**Environment**

- Version: v0.38.9-beta.1
- Environment: OS X, Docker

**Additional context**

I've been able to reproduce locally and debug the code a bit, here's what I found:

1. The request handler [initializes](https://github.com/ory/oathkeeper/blob/6d3555101b1d6f2dc95db49c3286ac6024f43720/proxy/request_handler.go#L182) the [empty subject](https://github.com/ory/oathkeeper/blob/6d3555101b1d6f2dc95db49c3286ac6024f43720/proxy/request_handler.go#L338-L340)
2. `noop` authenticator is found and [request gets flagged](https://github.com/ory/oathkeeper/blob/6d3555101b1d6f2dc95db49c3286ac6024f43720/proxy/request_handler.go#L238-L243) as being able to proceed (`found = true`).
3. `id_token` mutator [gets invoked](https://github.com/ory/oathkeeper/blob/6d3555101b1d6f2dc95db49c3286ac6024f43720/proxy/request_handler.go#L321) with the empty subject and the JWT gets [assigned to the `Authorization` header](https://github.com/ory/oathkeeper/blob/master/pipeline/mutate/mutator_id_token.go#L201).

Trying to get some clarification on whether the docs are simply out of date and the behavior was changed at some point. Or if this is a bug. Thanks!
