### ISSUE TITLE
Document how to configure minimal errors/mutator handlers

### ISSUE THREAD

**Issue by pingiun** [ory/oathkeeper#725]
**Describe the bug**

When setting the header mutator to enabled, the oathkeeper server doesn't start.

**Reproducing the bug**

Start the oathkeeper service with the below configuration

_Server logs_

```
time=2021-05-15T14:28:21Z level=info msg=Config file loaded successfully. audience=application path=/local/oathkeeper.yml service_name=oathkeeper service_version=
time=2021-05-15T14:28:21Z level=error msg=The provided configuration is invalid and could not be loaded. Check the output below to understand why. audience=application config_file=/local/oathkeeper.yml service_name=oathkeeper service_version=

mutators.header: map[enabled:true]
                 ^-- oneOf failed

mutators.header.config: <nil>
                        ^-- one or more required properties are missing

mutators.header.enabled: true
                         ^-- value must be false

time=2021-05-15T14:28:21Z level=fatal msg=The services failed to start because the configuration is invalid. Check the output above for more details. audience=application service_name=oathkeeper service_version=
```

_Server configuration_

```yaml
---
access_rules:
  matching_strategy: glob
  repositories:
  - file:///local/access-rules.yml
authenticators:
  anonymous:
    config:
      subject: guest
    enabled: true
  noop:
    enabled: true
authorizers:
  allow:
    enabled: true
  deny:
    enabled: true
mutators:
  noop:
    enabled: true
  header:
    enabled: true
serve:
  proxy:
    tls:
      cert:
        path: /local/cloudflare_origin
      key:
        path: /local/cloudflare_origin_key
version: v0.38.11-beta.1
```

**Expected behavior**

Oathkeeper starts up with the header mutator enabled

**Environment**

- Version: oryd/oathkeeper:v0.38.11-beta.1
- Environment: Docker started by nomad

**Additional context**

I also tried adding `config: {}` to the header mutator config but that didn't help, it only works when I set `enabled: false` which doesn't help of course.

**Comment by pingiun** [comment]
I searched the issue tracker and found nothing about this yet so it seems I'm just doing something wrong? (In which case I'd argue this isn't documented properly). Or maybe nobody uses this mutator

**Comment by pingiun** [comment]
I did indeed configure this incorrectly, a minimal configuration for the header mutator seems to be:

```yaml
mutators:
  header:
    enabled: true
    config: 
      headers: {}
```

Seems like just setting enabled to true should be sufficient
