### ISSUE TITLE
oAthkeeper not returning proper cors headers

### ISSUE THREAD

**Issue by Reivals** [ory/oathkeeper#742]
**Describe the bug**
When running the oAthKeeper in decisions mode (https://www.ory.sh/oathkeeper/docs/#access-control-decision-api), when oathkeeper will deny the request, despite proper cors configuration, it doesn't return the CORS headers.  Interestingly oathkeeper will return proper CORS headers when the request will succeed.

**Reproducing the bug**

1. Create applications setup where oathkeeper is running in decisions mode.
2. Trigger request which not be authenticated by oathkeeper.
3. Recieve request with no CORS headers.

_Server configuration_

Configuration of oathkeeper
```
  config:
    #  If set, uses the given access rules.
    access_rules:
      repositories:
        - file:///etc/rules/access-rules.json
    serve:
      api:
        port: 4456
        # Cors configuration in order to let preflight requests without authentication
        cors:
          enabled: true
```

**Expected behavior**

Oathkeeper returns CORS headers always, despite the fact whether the request was authenticated or not.

**Environment**

image:
  repository: docker.io/oryd/oathkeeper
  tag: v0.38.9-alpine
