### ISSUE TITLE
Authenticator bearer_token token_from query_parameter does not forward token to check_session_url if preserve_path: true

### ISSUE THREAD

**Issue by hunzikerj** [ory/oathkeeper#786]
**Describe the bug**

The bearer_token authenticator does only forward request method/path/headers. If preserve_path is set to true then the query_parameter will not get forwarded as the url is replaced by the check_session_url.

**Reproducing the bug**

Using Oathkeeper according to the example in the documentation.

```
# Some Access Rule Preserving Path: access-rule-2.yaml
id: access-rule-2
# match: ...
# upstream: ...
authenticators:
  - handler: bearer_token
    config:
      check_session_url: https://session-store-host/check-session
      token_from:
        query_parameter: auth-token
      preserve_path: true
```

**Expected behavior**

If preserve_path is set to true then the query_parameter should be appended to the check_session_url in the request.

Example:

`https://session-store-host/check-session?auth-token=xxx`

**Environment**

- Version: v0.38.12-beta.1
