### ISSUE TITLE
Empty Subject value, how to?

### ISSUE THREAD

**Issue by frederikhors** [ory/oathkeeper#793]
**Describe the bug**

It prints empty value for `X-User: '{{ print .Subject }}'` using Header Mutator.

I'm following the docs but I don't know how to properly configure yaml config files for it to work.

_Server configuration_

- oathkeeper.yml

```yml
access_rules:
  repositories:
    - file:///etc/config/oathkeeper/access-rules.yml

authenticators:
  anonymous:
    enabled: true
  noop:
    enabled: true
  cookie_session:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      # extra_from: "@this"
      # subject_from: "identity.id"
      # subject_from: "@this"
      # subject_from: "identity"
      # subject_from: "subject"
      # I tried so much values! But I wanna stick with the default ones!
      only:
        - ory_kratos_session

errors:
  fallback:
    - redirect
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: http://localhost:4000
        when:
          - request:
              header:
                accept:
                  - text/*

authorizers:
  allow:
    enabled: true

mutators:
  noop:
    enabled: true
  header:
    enabled: true
    config:
      headers:
        X-User: "{{ print .Subject }}"
        # X-User: "{{ print .subject }}"
        # What to use here???
        X-Custom-Trait: "{{ print .Subject.traits.custom_trait }}"

log:
  level: debug
  leak_sensitive_values: true

serve:
  proxy:
    port: 4455
  api:
    port: 4456
```

**Environment**

- Version: oryd/oathkeeper:v0.38.14-beta.1, oryd/kratos:v0.7.0-alpha.1
- Environment: Docker

**Comment by frederikhors** [comment]
My identity from `/sessions/whoami` is:

```json
{
  "id": "e11e7b71-19ae-4cd7-ad80-74638975c4f0",
  "active": true,
  "expires_at": "2021-08-17T12:58:51.220453Z",
  "authenticated_at": "2021-07-18T12:58:51.220453Z",
  "issued_at": "2021-07-18T12:58:51.220472Z",
  "identity": {
    "id": "7192d879-4db2-4f57-a1c9-d9eb24609a73",
    "schema_id": "default",
    "schema_url": "http://localhost:4455/schemas/default",
    "state": "active",
    "state_changed_at": "2021-07-18T12:51:07.258347Z",
    "traits": {
      "image": "/image.png",
      "email": "custom@email.com",
      "is_admin": true,
      "lastname": "Bob",
      "firstname": "John",
      "company_id": "123"
    },
    "recovery_addresses": [
      {
        "id": "afa66ed1-4733-44a9-b75e-26f72654788f",
        "value": "custom@email.com",
        "via": "email",
        "created_at": "2021-07-18T12:51:07.260237Z",
        "updated_at": "2021-07-18T12:51:07.260237Z"
      }
    ],
    "created_at": "2021-07-18T12:51:07.25953Z",
    "updated_at": "2021-07-18T12:51:07.25953Z"
  }
}
```

**Comment by frederikhors** [comment]
@aeneasr, this is blocking for me and I know very well that this is not so important to you and to the rest of the world, but if by the utmost grace and kindness you wanted to help me understand I would be grateful to you forever.

Thank you.

**Comment by frederikhors** [comment]
If I use this config:

```yml
authenticators:
  cookie_session:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      subject_from: "identity"
        
mutators:
  header:
    enabled: true
    config:
      headers:
        X-User: "{{ print .Subject.id }}"
        X-Company-ID: "{{ print .Subject.traits.company_id }}"
```

I get this error:

```
Access credentials are not sufficient to access this resource reason=The configured subject_from GJSON path returned an error on JSON output: json: cannot unmarshal object into Go value of type string request-id= status=403 writer=JSON
```

**Comment by aeneasr** [comment]
Hey there, this is the config we are using:

```
    cookie_session: {
      enabled: true,
      config: {
        check_session_url: 'http://<kratos>/sessions/whoami',
        preserve_path: true,
        extra_from: '@this',
        subject_from: 'identity.id',
        only: ['ory_session_ory'],
        preserve_host: true,
      },
    },
```

Hope this helps!

**Comment by aeneasr** [comment]
Combining it with:

```
  header:
    enabled: true
    config:
      headers:
        X-User: "{{ print .Subject }}"
```

should do what you want. If you want extra infos, you probably need to do something like this:

```
        X-Company-ID: "{{ print .Extra.identity.traits.company_id }}"
```

Howver I am not sure how well this works. Maybe try it with this first:

```
        X-User-Extra: "{{ print .Extra.identity }}"
```
