### ISSUE TITLE
0.38.14-beta.1 remote_json without forward_response_headers_to_upstream gives obscure error

### ISSUE THREAD

**Issue by radekg** [ory/oathkeeper#797]
**Describe the bug**

```
oathkeeper_1                  | authorizers.remote_json: map[config:map[forward_response_headers_to_upstream:<nil> payload:{
oathkeeper_1                  |     "namespace": "...",
oathkeeper_1                  |     "subject": "...",
oathkeeper_1                  |     "object": "...",
oathkeeper_1                  |     "relation": "..."
oathkeeper_1                  | }
oathkeeper_1                  |  remote:http://keto:4466/check] enabled:true]
oathkeeper_1                  |                          ^-- oneOf failed
oathkeeper_1                  |
oathkeeper_1                  | authorizers.remote_json.config: map[forward_response_headers_to_upstream:<nil> payload:{
oathkeeper_1                  |     "namespace": "...",
oathkeeper_1                  |     "subject": "...",
oathkeeper_1                  |     "object": "...",
oathkeeper_1                  |     "relation": "..."
oathkeeper_1                  | }
oathkeeper_1                  |  remote:http://keto:4466/check]
oathkeeper_1                  |                                 ^-- doesn't validate with "#/definitions/configAuthorizersRemoteJSON"
oathkeeper_1                  |
oathkeeper_1                  | authorizers.remote_json.config.forward_response_headers_to_upstream: <nil>
oathkeeper_1                  |                                                                      ^-- expected array, but got null
oathkeeper_1                  |
oathkeeper_1                  | authorizers.remote_json.enabled: true
oathkeeper_1                  |                                  ^-- value must be false
```

It is not possible to set the value of `authorizers.remote_json.enabled` to `true`.

**Reproducing the bug**

Set the

```yaml
authorizers:
    allow:
        enabled: true
    deny:
        enabled: true
    remote_json:
        # remote_json documentation: https://www.ory.sh/oathkeeper/docs/pipeline/authz#remote_json
        enabled: true
        config:
            remote: http://keto:4466/check
            payload: |
                {
                    "namespace": "...",
                    "subject": "...",
                    "object": "...",
                    "relation": "..."
                }
```

on a running oathkeeper. Changing the config to:

```yaml
authorizers:
    allow:
        enabled: true
    deny:
        enabled: true
    remote_json:
        # remote_json documentation: https://www.ory.sh/oathkeeper/docs/pipeline/authz#remote_json
        enabled: true
        config:
            remote: http://keto:4466/check
            forward_response_headers_to_upstream: []
            payload: |
                {
                    "namespace": "...",
                    "subject": "...",
                    "object": "...",
                    "relation": "..."
                }
```

Fixes the problem.
