### ISSUE TITLE
Oauthkeeper does not route to the upstream server with correct address with docker compose

### ISSUE THREAD

**Issue by DanielChuDC** [ory/oathkeeper#848]
**Describe the bug**

Hi I would like to ask how the oauthkeeper able to route to the upstream server url with docker compose service name?

I always gotten ` http: proxy error: dial tcp 127.0.0.1:8000: connect: connection refused`
while the rules.json specific the upstream url as `http://<docker-compose-service-name>`

**Reproducing the bug**

example of the rules.json
```
 {
    "id": "allow-access-to-protect-resource-with-jwt-authorizer",
    "version": "v0.38.0-beta.1",
    "upstream": {
      "url": "http://auth"
    },
    "match": {
      "url": "http://<127.0.0.1|localhost>:4455/secret",
      "methods": [
        "POST","GET"
      ]
    },
    "authenticators": [
      {
        "handler": "jwt",
        "allowed_algorithms": ["HS256","EdDSA", "ES256"]
      }
    ],
    "authorizer": {
      "handler": "allow"
    },
    "mutators": [
      {
        "handler": "noop"
      }
    ]
  }
```

_Server logs_

_Server configuration_

**Expected behavior**

Expected the Oathkeeper able to route me to the upstream url once the authentication completed.

**Environment**

On Mac Big Sur, using `oryd/oathkeeper:v0.38.12-beta.1`

**Additional context**

docker-compose.yml
```
# Use postgres/example user/password credentials
version: '3.1'

services:
  auth:
    build: ./backend/auth/
    ports: 
      - 8000:8000
    networks:
      - deploy_network
    deploy:
      replicas: 1
  
  oath-keeper:
    build: ./backend/oathkeeper-demo/
    ports: 
      - 4455:4455
      - 4456:4456
    networks:
      - deploy_network
    deploy:
      replicas: 1
    depends_on:
      - "auth"
    command:
      serve --config=config.yaml

networks:
  deploy_network:
    driver: bridge
```
