### ISSUE TITLE
Environment variables in access rules or other type of variable substitution

### ISSUE THREAD

**Issue by viters** [ory/oathkeeper#853]
Hey,

I am using Ory Oathkeeper in my project right now (by the way, awesome work with Ory overall!). I will deploy it to multiple environments and I've came to conclusion, that the only difference between access rules on different environments I will have are base URLs on matchers and upstreams.

Example:
```yaml
- id: 'service'
  upstream:
    preserve_host: true
    url: 'http://service:8000'
    strip_path: /.service
  match:
    url: 'http://localhost:4455/.service'
    methods:
      - OPTIONS
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
 ```

This is access rule defined for local environment, the same service will be later deployed to production, but the URLs will change. Maybe access rules definition could allow for:

```yaml
- id: 'service'
  upstream:
    preserve_host: true
    url: '$SERVICE_URL'
    strip_path: /.service
  match:
    url: '$PUBLIC_PATH/.service'
    methods:
      - OPTIONS
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
 ```
