### ISSUE TITLE
Configuration is invalid when adding bearer_token authenticator

### ISSUE THREAD

**Issue by RukolaHasser** [ory/oathkeeper#878]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I added `bearer_token` to the configuratino and deployed oathkeeper in k8s via `helm`, but it constantly failed with the same error: ` ^-- additionalProperties "bearer_token" not allowed`.
I tried the same config on my local machine and it worked, I figure the syntax should be correct.

### Reproducing the bug

In the `oathkeeper.yaml` `authenticators` section, add the following:
```
    authenticators:
      cookie_session:
        enabled: true
        config:
          check_session_url: http://analytics-kratos-public.staging/sessions/whoami
          preserve_path: true
          extra_from: "@this"
          subject_from: "identity.id"
          only:
            - ory_kratos_session
      anonymous:
        enabled: true
        config:
          subject: guest
      noop:
        enabled: true
      bearer_token:
        enabled: true
        config:
          check_session_url: http://analytics-auth.staging.svc.cluster.local:9990/auth
          preserve_path: true
```

Run `helm upgrade -n staging -f oathkeeper.yaml oathkeeper ory/oathkeeper` (for my staging env)

### Relevant log output

```shell
time=2021-11-29T12:23:05Z level=info msg=Config file loaded successfully. audience=application path=/etc/config/config.yaml service_name=oathkeeper service_version=
time=2021-11-29T12:23:05Z level=error msg=The provided configuration is invalid and could not be loaded. Check the output below to understand why. audience=application config_file=/etc/config/config.yaml service_name=oathkeeper service_version=

authenticators: map[anonymous:map[config:map[subject:guest] enabled:true] bearer_token:map[config:map[check_session_url:http://analytics-kratos-public.staging/sessions/whoami preserve_path:true] enabled:true] cookie_session:map[config:map[check_session_url:http://analytics-kratos-public.staging/sessions/whoami extra_from:@this only:[ory_kratos_session] preserve_path:true subject_from:identity.id] enabled:true] jwt:map[config:map[scope_strategy:none] enabled:false] noop:map[enabled:true] oauth2_client_credentials:map[config:map[retry:map[give_up_after:1s max_delay:100ms]] enabled:false] oauth2_introspection:map[config:map[cache:map[enabled:false] pre_authorization:map[enabled:false] retry:map[give_up_after:1s max_delay:100ms] scope_strategy:none] enabled:false] unauthorized:map[enabled:false]]
                ^-- additionalProperties "bearer_token" not allowed

time=2021-11-29T12:23:05Z level=fatal msg=The services failed to start because the configuration is invalid. Check the output above for more details. audience=application service_name=oathkeeper service_version=
```

### Version

 Helm chart 0.21.1

**Comment by antaka1** [comment]
+1 , I am getting this as well, also oathkeeper-maester is complaining about this 
`2022-01-27T11:17:15.914Z    INFO    controllers.Rule    validation error in Rule ory/customer-rules: "invalid handlers: [authenticator/bearer_token], please check the configuration"`

**Comment by aeneasr** [comment]
@antaka1 your issue seems to be related with the controller, please report the issue over there :)

Regarding the original issue, this has been resolved on master!

**Comment by adamstrawson** [comment]
@antaka1 The error you're seeing is a configuration issue, there's a [default list ](https://github.com/ory/oathkeeper-maester/blob/master/main.go#L41 )of authenticators available, which `bearer_token` isn't one.  You need to override these defaults to include `bearer_token`

Assuming you're deploying with helm, you can add the below to your helm values (Edit to match which authenticators you need to use);

```yaml
    oathkeeper-maester:
      deployment:
        env:
        - name: authenticatorsAvailable
          value: '[noop, unauthorized, anonymous, bearer_token, cookie_session, oauth2_client_credentials, oauth2_introspection, jwt]'
```
