### ISSUE TITLE
Provide Context for Access Rule Errors

### ISSUE THREAD

**Issue by KrishnaManohar1997** [ory/oathkeeper#938]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Consider the following as our Access Rule file being used in the config

access_rules.json

```
[
  {
    "id": "asd2",
    "version": "v0.1",
    "upstream": {
      "url": "https://httpbin.org/get",
      "preserve_host": true
    },
    "match": {
      "url": "http://127.0.0.1:4455/get",
      "methods": ["GET", "POST"]
    },
    "authenticators": [{ "handler": "noop" }],
    "authorizer": { "handler": "allow" },
    "mutators": [{ "handler": "noop" }],
    "errors": [{ "handler": "json" }]
]

```

We will end up with the following issue, which doesn't 

`unable to update access rules from given location, changes will be ignored. Check the configuration or restart the service if the issue persists.  audience=application error=map[message:No Major.Minor.Patch elements found] file=access-rule-1.json service_name=ORY Oathkeeper service_version=v0.38.23-beta.1`

1. The issue is related to the **`"version"`** , it should follow **Semantic Versioning**  which is mentioned in the documentation [here](https://www.ory.sh/docs/oathkeeper/api-access-rules#access-rule-format)
2. It'd be more helpful if the field causing the error/issue can be added in the error
3. Documentation for access rules can be improved if the (Optional, Required) labels are added

For instance:

_**`<FIELD_NAME> doesn't match the <CRITERIA>`**_

### Reproducing the bug

Steps to Reproduce

1. Use any of preferred method to deploy oathkeeper (I personally used Helm Chart)
2. Add the path/link to the above access_rules.json file in the oathkeeper config

### Relevant log output

```shell
unable to update access rules from given location, changes will be ignored. Check the configuration or restart the service if the issue persists. audience=application error=map[message:No Major.Minor.Patch elements found] file=access-rule-1.json service_name=ORY Oathkeeper service_version=v0.38.23-beta.1
```

### Relevant configuration

```yml
[
  {
    "id": "asd2",
    "version": "v0.1",
    "upstream": {
      "url": "https://httpbin.org/get",
      "preserve_host": true
    },
    "match": {
      "url": "http://127.0.0.1:4455/get",
      "methods": ["GET", "POST"]
    },
    "authenticators": [{ "handler": "noop" }],
    "authorizer": { "handler": "allow" },
    "mutators": [{ "handler": "noop" }],
    "errors": [{ "handler": "json" }]
]
```

### Version

Helm Chart Version 0.22.1 App Version -

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Kubernetes with Helm
