### ISSUE TITLE
Oathkeeper does not support using .MatchContext.RegexpCaptureGroups using glob matching strategy.

### ISSUE THREAD

**Issue by gen1us2k** [ory/oathkeeper#946]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

A detailed explanation can be found in this [discussion](https://github.com/ory/oathkeeper/discussions/933). I assume that oathkeeper has this issue because of missing implementation of [FindStringSubmatch](https://github.com/ory/oathkeeper/blob/69ad28f87fd4f49e1ca5ed0d4bd1099b61a795a5/rule/engine_glob.go#L35) and [ReplaceAllString](https://github.com/ory/oathkeeper/blob/69ad28f87fd4f49e1ca5ed0d4bd1099b61a795a5/rule/engine_glob.go#L30) methods for globMatchingEngine

### Reproducing the bug

set `matchingStrategy: glob` and use these access rules

```
- id: allow-test
  upstream:
    url: http://host.docker.internal:8080/
    preserve_host: true
  match:
    url: http://localhost:4455/<{*,*/*}>
    methods:
    - GET
  authenticators:
  - handler: noop
  authorizer:
    handler: allow
  mutators:
  - handler: header
    config:
      headers:
        X-Groups: "{{ printIndex .MatchContext.RegexpCaptureGroups 0  }}"
```

 ----- Request Start ----->
Method:          GET
Path:            /foo/bar

Headers:
X-Groups:        
X-Header:        map[Accept:[*/*] User-Agent:[curl/7.77.0]]
X-Method:        GET
X-Url:           http://localhost:4455/foo/bar  
<----- Request End -----

### Version

v0.38.23-beta.1
