### ISSUE TITLE
Glob pattern matcher incorrectly includes separators in some cases

### ISSUE THREAD

**Issue by emnicolas** [ory/oathkeeper#963]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I believe separators used by OathKeeper are `.` and `/`. Neither should be matched by wildcard `*` (one or zero chars) and `?` (precisely one char):
```yaml
url: "http://something/<1?2>"
# matches `1x3` but not `1.2`, `1/2`, or `12`

url: "http://something/<1*4>"
# matches `1x4`, `1xx4` or `14`, but not `1.4`, `1/4`
```

However  this is counterintuitive and feels more like a bug:
```yaml
https://admin.emcloud.local/123/4
url: "http://something/<????*>"
# while the above correctly doesn't match `123/4`...

url: "http://something/<{,????*}>"
# this correctly matches `1234`, `12345`, and not `123`,
# BUT incorrectly matches ALSO `123/4`, `123.4` and `1/234`!?!?!
```

FYI: works as _expected_ on glob checkers like [globster](https://globster.xyz/).

Note: I understand that the issue, if indeed a bug, is likely coming from the glob library rather than OathKeeper or its config. Nonetheless, this is a bit of an issue with Oathkeeper's usability IMO and the glob library does not seem to be maintained anymore.

### Remark on a related useful missing glob feature

A common use case is to exclude just some specific sub directories (ex: match everything not going to the `/api/` path) but otherwise match nearly everything else. This helps avoid issues with multiple rules matching when one is applied to a subdirectory before a main catch all.

However [gobwas/glob](https://github.com/gobwas/glob) does not support some useful glob patterns which would make this much easier:
```yaml
# this will not work, we cannot negate a whole string unfortunately
url: "http://something/<!(api/)**>"

# but since this does work:
url: "http://something/<[!a]>"
# matches `b`, `6`, `_`... but not `a`

# then to reliably exclude `api/**` routes we must actually include [nearly] everything else:
url: "http://something/<{,*,.*,*.*,.*/**,?/**,??/**,[!a][!p][!i]/**,???[!\\/]*/**}>"
# the last part (`???[!\\/]*/**`) is needed to include everything with 4 or more char in the first level dir
# to see why we cannot just use `????*/**` see this issue
```

### Reproducing the bug

1. use the `glob` matching pattern
2. set up a rule with `/<{,????*}>`
3. try to access a route like `/123/4` or `1/234` => works, when it should throw a `Requested url does not match any rules` error

### Relevant configuration

```yml
# main config
access_rules:
  matching_strategy: glob

# rule
match:
    url: "http://something/<{,????*}>"
    methods:
      - GET
```

### Version

Docker `oryd/oathkeeper:v0.38.11-beta.1-alpine`

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose
