### ISSUE TITLE
path specified in strip_path is not stripped

### ISSUE THREAD

**Issue by a0v0** [ory/oathkeeper#976]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Path prefix specified in strip_path is not stripped

### Reproducing the bug

IDK

### Relevant log output

```shell
oryfane-oathkeeper-1      | {"audience":"application","error":{"debug":"","message":"Requested url does not match any rules","reason":"","status":"Not Found","status_code":404},"granted":false,"http_host":"127.0.0.1:4455","http_method":"GET","http_url":"http://127.0.0.1:4455/auth/v1/sessions/whoami","http_user_agent":"insomnia/2022.4.1","level":"warning","msg":"Access request denied","service_name":"ORY Oathkeeper","service_version":"v0.38.25-beta.1","time":"2022-06-27T00:52:54Z"}

oryfane-oathkeeper-1      | {"code":404,"debug":"","details":{},"error":"Requested url does not match any rules","level":"error","msg":"An error occurred while handling a request","reason":"","request-id":"","status":404,"time":"2022-06-27T00:52:54Z","writer":"JSON"}

oryfane-oathkeeper-1      | {"http_request":{"headers":{"accept":"*/*","user-agent":"insomnia/2022.4.1"},"host":"127.0.0.1:4455","method":"GET","path":"/auth/v1/sessions/whoami","query":null,"remote":"172.20.0.1:34720","scheme":"http"},"http_response":{"status":404,"text_status":"Not Found","took":272800},"level":"info","msg":"completed handling request","time":"2022-06-27T00:52:54Z"}
```

### Relevant configuration

```yml
# access-rules.json

- id: "iam:ory-kratos"
  upstream:
    preserve_host: false
    url: "http://kratos:4433"
    strip_path: "/auth/v1"
  match:
    url: "http://127.0.0.1:4455/auth/v1/<**>" 
    methods:
      - "*"
  authenticators:
    - handler: noop
  mutators:
    - handler: noop
  authorizer:
    handler: allow
```

### Version

v0.38.25

### On which operating system are you observing this issue?

Other

### In which environment are you deploying?

Docker
